//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoDataConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoDataConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking existence of data item with id:.
        /// </summary>
        internal static string ___Checking_existence_of_data_item_with_id___ {
            get {
                return ResourceManager.GetString("___Checking_existence_of_data_item_with_id___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating data item with id:.
        /// </summary>
        internal static string ___Creating_data_item_with_id___ {
            get {
                return ResourceManager.GetString("___Creating_data_item_with_id___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating or updating data item with id:.
        /// </summary>
        internal static string ___Creating_or_updating_data_item_with_id___ {
            get {
                return ResourceManager.GetString("___Creating_or_updating_data_item_with_id___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting data item with id:.
        /// </summary>
        internal static string ___Deleting_data_item_with_id___ {
            get {
                return ResourceManager.GetString("___Deleting_data_item_with_id___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ___ID__ {
            get {
                return ResourceManager.GetString("___ID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading data item with id:.
        /// </summary>
        internal static string ___Reading_data_item_with_id___ {
            get {
                return ResourceManager.GetString("___Reading_data_item_with_id___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating data item with id:.
        /// </summary>
        internal static string ___Updating_data_item_with_id___ {
            get {
                return ResourceManager.GetString("___Updating_data_item_with_id___", resourceCulture);
            }
        }
    }
}
