<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Sequence1Task" Id="{89b1e532-b6f8-0454-03d0-32f4a253f9c7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Sequence1Task EXTENDS TcoCore.TcoTask
VAR_INPUT
	Sequence : TcoCore.ITcoSequencer;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Restore" Id="{a112eac4-68ee-051d-31ca-5473b9d21645}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Restores this instance to the Ready state. Can be called explicitly or from within one of the restore mechanisms.
			<para>
				See also <see cref="PlcDocu.TcoCore.TcoTask.AutoRestorable()"/>
			</para>
		</summary>			
	</docu>	
~*)
METHOD Restore : ITcoRestorable]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.Restore();
THIS^.Sequence.Restore();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>