<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="TcoAnalogueInspectorTests" Id="{8dc99e3a-e964-0734-3e39-363ce73c5757}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcoAnalogueInspectorTests EXTENDS TcoInspectorTests
VAR
    _sut            : TcoInspectors.TcoAnalogueInspector(THIS^, TcoCore.NO.Structure);
    _inspectedValue : LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <Method Name="Inspect" Id="{3703065d-567a-0583-2b5d-991c71f6123a}">
      <Declaration><![CDATA[METHOD Inspect : TcoInspectors.IInspector]]></Declaration>
      <Implementation>
        <ST><![CDATA[Inspect := _sut.Inspect(_inspectedValue);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Main" Id="{060cfbf3-cf54-0d00-1452-4a68e42aa954}">
      <Declaration><![CDATA[METHOD PROTECTED Main
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.Main();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WithCoordinator" Id="{9d0edf65-b764-0fe1-0ea6-c44ac1de6e92}">
      <Declaration><![CDATA[METHOD  WithCoordinator : REFERENCE TO TcoInspectorTests
VAR_INPUT
	inoCoordinator : TcoCore.ITcoCoordinator;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_sut.WithCoordinator(_coordinator);
WithCoordinator REF= THIS^;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>