<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="fbManipulatorAutomat" Id="{e3bf80e0-2686-0576-2ba1-7979512bbe7c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbManipulatorAutomat EXTENDS TcoCore.TcoState
VAR
	_horizontalPiston : fbPiston(THIS^);
	_verticalPiston : fbPiston(THIS^);
	_gripperPiston : fbPiston(THIS^);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_horizontalPiston();
_verticalPiston();
_gripperPiston();

IF(THIS^.State = 0) THEN	
	IF(_verticalPiston.MoveUp().Done 
		AND_THEN _horizontalPiston.MoveLeft().Done 
		AND_THEN _gripperPiston.Open().Done) THEN
		THIS^.ChangeState(10);
	END_IF
END_IF

IF(THIS^.State = 10) THEN
	IF(_verticalPiston.MoveDown().Done) THEN
		THIS^.ChangeState(20);
	END_IF
END_IF

IF(THIS^.State = 20) THEN
	IF(_gripperPiston.Close().Done) THEN
		THIS^.ChangeState(30);
	END_IF
END_IF

IF(THIS^.State = 30) THEN
	IF(_verticalPiston.MoveUp().Done) THEN
		THIS^.ChangeState(40);
	END_IF
END_IF

IF(THIS^.State = 40) THEN
	IF(_horizontalPiston.MoveRight().Done) THEN
		THIS^.ChangeState(50);
	END_IF
END_IF

IF(THIS^.State = 50) THEN
	IF(_verticalPiston.MoveDown().Done) THEN
		THIS^.ChangeState(60);
	END_IF
END_IF

IF(THIS^.State = 60) THEN
	IF(_gripperPiston.Open().Done) THEN
		THIS^.ChangeState(0);
	END_IF
END_IF]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>