<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="fbManipulatorAutomat" Id="{e3bf80e0-2686-0576-2ba1-7979512bbe7c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbManipulatorAutomat EXTENDS TcoCore.TcoState
VAR
	_horizontalPiston : fbPiston(THIS^);
	_verticalPiston : fbPiston(THIS^);
	_gripperPiston : fbPiston(THIS^);
	_persistentMessage : TcoCore.TcoMessenger(THIS^);
END_VAR
VAR
	ar : ARRAY[0..1] OF BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// THIS^.Context.Environment.Messaging.Suspend();


_persistentMessage.OnCondition(ar[0]).Error('this is persistent error 1').Pin();
_persistentMessage.OnCondition(ar[1]).Error('this is persistent error 2').Pin();


THIS^._verticalPiston.Messenger.OnCondition(THIS^.Context.StartCycleCount MOD 5000 = 0).Post('We are running automatic mode4 conditional', eMessageCategory.Catastrophic).Pin();
THIS^.Messenger.OnCondition(THIS^.Context.StartCycleCount MOD 2500 = 0).Info('We are running automatic mode1 conditional').Pin();
THIS^._gripperPiston.Messenger.OnCondition(THIS^.Context.StartCycleCount MOD 1000 = 0).Notify('We are running automatic mode7 conditional').Pin();



//IF(THIS^.Context.StartCycleCount MOD 1 = 0) THEN 
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');	
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4-');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5-');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6-');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7-');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8-');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9-');
	THIS^.Messenger.Info('We are running automatic mode1-');
	THIS^.Messenger.Notify('We are running automatic mode2-');
	THIS^.Messenger.Notify('We are running automatic mode3-');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode48');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');
	THIS^.Messenger.Info('We are running automatic mode1');
	THIS^.Messenger.Notify('We are running automatic mode2');
	THIS^.Messenger.Notify('We are running automatic mode3');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode4');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode5');
	THIS^._verticalPiston.Messenger.Notify('We are running automatic mode6');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode7');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode8');
	THIS^._gripperPiston.Messenger.Notify('We are running automatic mode9');
//END_IF;

// THIS^.Context.Environment.Messaging.Resume();

_horizontalPiston();
_verticalPiston();
_gripperPiston();

IF(THIS^.State = 0) THEN	
	IF(_verticalPiston.MoveUp().Done 
		AND_THEN _horizontalPiston.MoveLeft().Done 
		AND_THEN _gripperPiston.Open().Done) THEN
		THIS^.ChangeState(10);
	END_IF
END_IF

IF(THIS^.State = 10) THEN
	IF(_verticalPiston.MoveDown().Done) THEN
		THIS^.ChangeState(20);
	END_IF
END_IF

IF(THIS^.State = 20) THEN
	IF(_gripperPiston.Close().Done) THEN
		THIS^.ChangeState(30);
	END_IF
END_IF

IF(THIS^.State = 30) THEN
	IF(_verticalPiston.MoveUp().Done) THEN
		THIS^.ChangeState(40);
	END_IF
END_IF

IF(THIS^.State = 40) THEN
	IF(_horizontalPiston.MoveRight().Done) THEN
		THIS^.ChangeState(50);
	END_IF
END_IF

IF(THIS^.State = 50) THEN
	IF(_verticalPiston.MoveDown().Done) THEN
		THIS^.ChangeState(60);
	END_IF
END_IF

IF(THIS^.State = 60) THEN
	IF(_gripperPiston.Open().Done) THEN
		THIS^.ChangeState(0);
	END_IF
END_IF]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>