<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MANIPULATOR" Id="{6ce25c6a-30a3-0b87-105c-f62d3a322039}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MANIPULATOR
VAR
	_context : fbManipulatorContext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_context.Run();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>