//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoCognexVisionTestsConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoCognexVisionTestsConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog inspector.
        /// </summary>
        public static string ___Analog_inspector__ {
            get {
                return ResourceManager.GetString("___Analog_inspector__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognex Designer.
        /// </summary>
        public static string ___Cognex_Designer__ {
            get {
                return ResourceManager.GetString("___Cognex_Designer__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inspector.
        /// </summary>
        public static string ___Data_inspector__ {
            get {
                return ResourceManager.GetString("___Data_inspector__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My very first DATAMAN.
        /// </summary>
        public static string ___My_very_first_DATAMAN__ {
            get {
                return ResourceManager.GetString("___My_very_first_DATAMAN__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My very first INSIGHT.
        /// </summary>
        public static string ___My_very_first_INSIGHT__ {
            get {
                return ResourceManager.GetString("___My_very_first_INSIGHT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PcToPlc.
        /// </summary>
        public static string ___PcToPlc__ {
            get {
                return ResourceManager.GetString("___PcToPlc__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlcToPc.
        /// </summary>
        public static string ___PlcToPc__ {
            get {
                return ResourceManager.GetString("___PlcToPc__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Specific Data.
        /// </summary>
        public static string ___Project_Specific_Data__ {
            get {
                return ResourceManager.GetString("___Project_Specific_Data__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultBool.
        /// </summary>
        public static string ___ResultBool__ {
            get {
                return ResourceManager.GetString("___ResultBool__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultInt.
        /// </summary>
        public static string ___ResultInt__ {
            get {
                return ResourceManager.GetString("___ResultInt__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultString.
        /// </summary>
        public static string ___ResultString__ {
            get {
                return ResourceManager.GetString("___ResultString__", resourceCulture);
            }
        }
    }
}
