<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL5151" Id="{d9913ae4-e866-027b-0d78-5bd81fc3db8c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL5151
VAR
	_io : EL5151_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAdsDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{72db3129-10e6-02e3-2af3-29e7f1df0746}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL5151_Data]]></Declaration>
      <Get Name="Get" Id="{664ffd42-e2f6-0c0a-2db4-b02447e0fbf0}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{aaa8b012-80a2-072a-38ed-08e4166830cb}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{30b64647-ad1d-0a1f-1ecb-1dad1964685d}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>