<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1252" Id="{72d01d1a-1267-0ddf-337f-31c848a57a87}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1252
VAR
	{attribute addProperty Name "CHANNEL_"}
	_io : EL1252_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{0112672b-d34d-08f7-3b13-ba74d9b8b143}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1252_Data]]></Declaration>
      <Get Name="Get" Id="{345a1be2-987d-0ff9-1189-e89f2a2be68a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{97f1665d-93d4-0cd5-2a57-36d8d4710db3}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{97eab6f9-4549-0fe6-0e8c-2f825abe4437}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>