<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2872" Id="{2d2e262f-747c-0ea6-2f72-84190a74e24a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2872
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2xx9_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{2fc8aa60-792d-0688-228d-224164a8ec22}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2xx9_Data]]></Declaration>
      <Get Name="Get" Id="{b6a3a333-9fcf-04bd-3bfc-80f50468f4ee}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{03848f57-4e84-078f-01b2-f200970594d0}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{2c936269-f70c-0c36-3089-54cf94207f5a}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>