<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2889" Id="{7fc73097-fc51-0668-3731-437221a97c9c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2889
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2xx9_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{2a8379de-7c1b-0219-35f9-93eda16fc069}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2xx9_Data]]></Declaration>
      <Get Name="Get" Id="{5aaa954b-2171-089a-0da7-5cadd576cf24}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{a21e8d1c-aeb4-0d6b-1bd1-75caf5d8794d}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{7234c157-1230-09d5-16eb-804775ba783d}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>