<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="EXAMPLES_PRG" Id="{74d7366d-b6fb-47e3-acf3-d19ebdfb665f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM EXAMPLES_PRG
VAR
	_context : fbContext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_context.Run();]]></ST>
    </Implementation>
    <LineIds Name="EXAMPLES_PRG">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>