<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1012" Id="{b5b6fd38-184d-02bc-0b68-66c70f1acd32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1012
VAR
	_io : EL1xx2_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{34dabf44-78de-0737-0e49-501ae5a77921}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1xx2_Data]]></Declaration>
      <Get Name="Get" Id="{6bb4c8d1-ded3-0cf0-344c-7bcfa3110a03}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{ce787ce7-a0fc-06c0-125d-0241105ba50f}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{b7b083a8-f1cd-04a0-2b7c-7e7ddde1aff6}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>