<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="DiagnosticsMessengers" Id="{e7f0eaf9-7f78-03a2-3372-f47f97235dbf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK DiagnosticsMessengers EXTENDS TcoCore.TcoObject
VAR
    Messengers : ARRAY[0..2] OF DiagnosticsMessenger(THIS^);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{0347ecc1-7879-0cac-2350-d28dd11b8839}">
      <Declaration><![CDATA[{attribute 'hide'}
METHOD FB_init : BOOL
VAR_INPUT
    bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
    bInCopyCode : BOOL; // if TRUE, the instance afterwards gets moved into the copy code (online change)
    ParentObject : ITcoObject;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Messengers[0].FB_init(bInitRetains, bInCopyCode, ParentObject);
Messengers[1].FB_init(bInitRetains, bInCopyCode, ParentObject);
Messengers[2].FB_init(bInitRetains, bInCopyCode, ParentObject);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>