<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{5b53fb17-cd82-0ea5-175c-64a7847dafcb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    myVeryFirstTcoContextInstance : myVeryFirstTcoContext;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[myVeryFirstTcoContextInstance.Run();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>