<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="SampleComponentTests" Id="{8976ba45-0863-0a6b-21c3-4f73a63db972}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SampleComponentTests EXTENDS _internals_TcoContext
VAR
	_sut : TcoCognexVision.SampleComponent(THIS^);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <Method Name="AddTwoNumbersTest" Id="{645d27ce-9e28-014e-310a-ae91dbed5602}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD INTERNAL AddTwoNumbersTest : INT
VAR_INPUT
	NumberOne : INT;
	NumberTwo : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[AddTwoNumbersTest := _sut.AddTwoNumbers(NumberOne, NumberTwo);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Main" Id="{72517ee4-edb7-004a-0cbc-276a16d1d561}">
      <Declaration><![CDATA[METHOD PROTECTED Main
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="WaitForModuloTest" Id="{9c3fc460-8a59-0447-1fcb-e51f84ec6aef}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD INTERNAL WaitForModuloTest : BOOL
VAR_INPUT
	Modulo : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[WaitForModuloTest := _sut.WaitForModulo(Modulo);
	]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>