//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoCoreExamplesConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoCoreExamplesConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Off.
        /// </summary>
        public static string ___Check_Off__ {
            get {
                return ResourceManager.GetString("___Check_Off__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check On.
        /// </summary>
        public static string ___Check_On__ {
            get {
                return ResourceManager.GetString("___Check_On__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks that the input is off.
        /// </summary>
        public static string ___Checks_that_the_input_is_off__ {
            get {
                return ResourceManager.GetString("___Checks_that_the_input_is_off__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks that the input is on.
        /// </summary>
        public static string ___Checks_that_the_input_is_on__ {
            get {
                return ResourceManager.GetString("___Checks_that_the_input_is_on__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string ___Disabled__ {
            get {
                return ResourceManager.GetString("___Disabled__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ___Enabled__ {
            get {
                return ResourceManager.GetString("___Enabled__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ___Off__ {
            get {
                return ResourceManager.GetString("___Off__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ___On__ {
            get {
                return ResourceManager.GetString("___On__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseting signal (off/false).
        /// </summary>
        public static string ___Reseting_signal__off_false___ {
            get {
                return ResourceManager.GetString("___Reseting_signal__off_false___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the output.
        /// </summary>
        public static string ___Resets_the_output__ {
            get {
                return ResourceManager.GetString("___Resets_the_output__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string ___Running__ {
            get {
                return ResourceManager.GetString("___Running__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the output.
        /// </summary>
        public static string ___Sets_the_output__ {
            get {
                return ResourceManager.GetString("___Sets_the_output__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting signal (on/true).
        /// </summary>
        public static string ___Setting_signal__on_true___ {
            get {
                return ResourceManager.GetString("___Setting_signal__on_true___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        public static string ___Signal__ {
            get {
                return ResourceManager.GetString("___Signal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string ___Stopped__ {
            get {
                return ResourceManager.GetString("___Stopped__", resourceCulture);
            }
        }
    }
}
