<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL5021" Id="{345c6611-19ff-077f-3bfe-ba8ba76ade19}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL5021
VAR
	_io : EL5021_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAdsDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{76cd271f-13fe-0970-047b-9c7d5d7b19ea}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL5021_Data]]></Declaration>
      <Get Name="Get" Id="{7f256521-f27b-00be-1139-d564d8971fd4}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{75c313a6-b4dc-0dcd-3637-9a5961c7b795}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{f2fe0719-60d2-06db-0370-120f170075ea}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>