//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoRexrothPressConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoRexrothPressConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string ___Config__ {
            get {
                return ResourceManager.GetString("___Config__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get last Results.
        /// </summary>
        internal static string ___Get_last_Results__ {
            get {
                return ResourceManager.GetString("___Get_last_Results__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reference: .
        /// </summary>
        internal static string ___Invalid_reference____ {
            get {
                return ResourceManager.GetString("___Invalid_reference____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing finished with error..
        /// </summary>
        internal static string ___Pressing_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Pressing_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing running..
        /// </summary>
        internal static string ___Pressing_running___ {
            get {
                return ResourceManager.GetString("___Pressing_running___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing started..
        /// </summary>
        internal static string ___Pressing_started___ {
            get {
                return ResourceManager.GetString("___Pressing_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing was aborted, while not yet completed!.
        /// </summary>
        internal static string ___Pressing_was_aborted__while_not_yet_completed___ {
            get {
                return ResourceManager.GetString("___Pressing_was_aborted__while_not_yet_completed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing was completed successfully..
        /// </summary>
        internal static string ___Pressing_was_completed_successfully___ {
            get {
                return ResourceManager.GetString("___Pressing_was_completed_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore executed!.
        /// </summary>
        internal static string ___Restore_executed___ {
            get {
                return ResourceManager.GetString("___Restore_executed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Task.
        /// </summary>
        internal static string ___Restore_Task__ {
            get {
                return ResourceManager.GetString("___Restore_Task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string ___Results__ {
            get {
                return ResourceManager.GetString("___Results__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Command.
        /// </summary>
        internal static string ___Run_Command__ {
            get {
                return ResourceManager.GetString("___Run_Command__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save last curve.
        /// </summary>
        internal static string ___Save_last_curve__ {
            get {
                return ResourceManager.GetString("___Save_last_curve__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ___Status__ {
            get {
                return ResourceManager.GetString("___Status__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for acknowledge Handle signal!.
        /// </summary>
        internal static string ___Waiting_for_acknowledge_Handle_signal___ {
            get {
                return ResourceManager.GetString("___Waiting_for_acknowledge_Handle_signal___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for ProgramActive!.
        /// </summary>
        internal static string ___Waiting_for_ProgramActive___ {
            get {
                return ResourceManager.GetString("___Waiting_for_ProgramActive___", resourceCulture);
            }
        }
    }
}
