<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Frederico_Object" Id="{a670f37d-a57d-030d-0c8c-d5d3d2bdaab6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Frederico_Object EXTENDS TcoCore.TcoObject
VAR
	_fredo 	:	AKid_Object(THIS^);	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>