<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="DefaultContext" Id="{9566aeb0-f006-4c52-ace4-7824786d839b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK DefaultContext EXTENDS TcoCore.TcoContext
VAR
	_wpfCyclinder : TcoPneumatics.Cylinder(THIS^);
	_wpfCyclinder_1 : TcoPneumatics.Cylinder(THIS^);
	_wpfCyclinder_2 : TcoPneumatics.Cylinder(THIS^);
	_wpfCyclinder_3 : TcoPneumatics.Cylinder(THIS^);
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Main" Id="{f765357f-253d-4bf2-baf0-fad144fcb997}">
      <Declaration><![CDATA[METHOD PROTECTED  Main]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.RtcSynchronize(TRUE, '', 60);

_wpfCyclinder.Service();	

_wpfCyclinder(inAtHomePos := IO.A1[0],
	inAtWorkPos := IO.A1[1],
	outToHomePos => IO.A2[0],
	outToWorkPos => IO.A2[1]);


]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>