<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="fbComponent" Id="{3a3f5739-2f9b-4ddf-a7b9-4efe8f16c6da}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT fbComponent
VAR
	{attribute addProperty Name "Components' message"}
	{attribute clr [ReadOnly()]}
	_message : STRING(255);
END_VAR
]]></Declaration>
    <Implementation>
      <CFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCImplementationObject">
              <o n="Items" t="CFCItemList">
                <l2 n="InnerList" />
              </o>
              <n n="ParameterInitializationMethodGenerator" />
              <o n="RoutingPathTable" t="CFCRoutingPathTable">
                <d2 n="InnerDictionary" />
              </o>
              <v n="AutoSizeCanvas">true</v>
              <v n="CanvasWidth">1</v>
              <v n="CanvasHeight">1</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
            <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
            <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
            <Type n="Int32">System.Int32</Type>
          </TypeList>
        </XmlArchive>
      </CFC>
    </Implementation>
    <Method Name="Info" Id="{4f2a9d49-7508-43d1-b8ca-30b80e325488}">
      <Declaration><![CDATA[METHOD PROTECTED Info
VAR_INPUT
	inMessage : STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_message := inMessage;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Manual" Id="{ebaeaa1d-acc8-400b-b205-2722550bd13c}">
      <Declaration><![CDATA[METHOD PUBLIC Manual

]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.ManualControl();]]></ST>
      </Implementation>
    </Method>
    <Method Name="ManualControl" Id="{06f21b03-8098-4a97-9d0b-2e50bc362267}">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT ManualControl

]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="fbComponent.Info">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="fbComponent.Manual">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="fbComponent.ManualControl">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>