<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1052" Id="{ae6f0455-d36a-0ecc-1d0f-eb6b8d0a25c5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1052
VAR
	_io : EL1052_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{3a4882e9-2ad9-0d71-358e-800b502c9409}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1052_Data]]></Declaration>
      <Get Name="Get" Id="{dded0e69-de51-07e9-1af9-3dc4dcc9e520}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{56932313-6963-0787-3cb9-f1e95bd325b4}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{f68e60f2-2f0b-0866-24a5-c979f10c8b62}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>