<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="TcoState" Id="{e15c5fcf-81d3-038e-202e-1cd87b834ace}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcoState EXTENDS TcoStateBase

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="ChangeState" Id="{8a2449de-98e2-0003-0ff6-3dd7ed17800f}">
      <Declaration><![CDATA[METHOD PUBLIC ChangeState : ITcoState
VAR_INPUT
	NewState : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ChangeState := SUPER^.ChangeStateProtected(NewState);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>