<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TcoStateExtendible" Id="{0382c192-a9cc-0bc0-35e0-92f74a06fb79}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT TcoStateExtendible EXTENDS TcoStateBase]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="ChangeState" Id="{bb1133c8-59fb-0b5a-0ba5-84fb713fd050}">
      <Declaration><![CDATA[METHOD PROTECTED FINAL ChangeState : ITcoState
VAR_INPUT
    NewState : INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[ChangeState := SUPER^.ChangeStateProtected(NewState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnStateChange" Id="{7e3711b4-64d6-0376-39cd-441141a47fe0}">
      <Declaration><![CDATA[(*~
    <docu>
        <summary>
            This method is called on each change of the <c>State</c>. This method could be overloaded and custom code should be placed here.
        </summary>
    </docu>
~*)
METHOD PROTECTED OnStateChange
VAR_INPUT
    PreviousState : INT;
    NewState : INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.OnStateChange(PreviousState, NewState);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>