<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TcoState" Id="{e15c5fcf-81d3-038e-202e-1cd87b834ace}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcoState EXTENDS TcoStateBase]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="ChangeState" Id="{8a2449de-98e2-0003-0ff6-3dd7ed17800f}">
      <Declaration><![CDATA[METHOD PUBLIC ChangeState : ITcoState
VAR_INPUT
    NewState : INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[ChangeState := SUPER^.ChangeStateProtected(NewState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnStateChange" Id="{3086bfc0-6684-0c18-3a68-e8c47053ddcc}">
      <Declaration><![CDATA[(*~
    <docu>
        <summary>
            This method is called on each change of the <c>State</c>. This method could be overloaded and custom code should be placed here.
        </summary>
    </docu>
~*)
METHOD PROTECTED OnStateChange
VAR_INPUT
    PreviousState : INT;
    NewState : INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.OnStateChange(PreviousState, NewState);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>