//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoPneumaticsTestsConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoPneumaticsTestsConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ___Home__ {
            get {
                return ResourceManager.GetString("___Home__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home position sensor.
        /// </summary>
        public static string ___Home_position_sensor__ {
            get {
                return ResourceManager.GetString("___Home_position_sensor__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In task.
        /// </summary>
        public static string ___In_task__ {
            get {
                return ResourceManager.GetString("___In_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Home.
        /// </summary>
        public static string ___Move_Home__ {
            get {
                return ResourceManager.GetString("___Move_Home__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE HOME a.
        /// </summary>
        public static string ___MOVE_HOME_a__ {
            get {
                return ResourceManager.GetString("___MOVE_HOME_a__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE HOME SWEET HOME.
        /// </summary>
        public static string ___MOVE_HOME_SWEET_HOME__ {
            get {
                return ResourceManager.GetString("___MOVE_HOME_SWEET_HOME__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to home position actuator.
        /// </summary>
        public static string ___Move_to_home_position_actuator__ {
            get {
                return ResourceManager.GetString("___Move_to_home_position_actuator__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Work.
        /// </summary>
        public static string ___Move_to_Work__ {
            get {
                return ResourceManager.GetString("___Move_to_Work__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE TO WORK a.
        /// </summary>
        public static string ___MOVE_TO_WORK_a__ {
            get {
                return ResourceManager.GetString("___MOVE_TO_WORK_a__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE TO WORK HARD WORK.
        /// </summary>
        public static string ___MOVE_TO_WORK_HARD_WORK__ {
            get {
                return ResourceManager.GetString("___MOVE_TO_WORK_HARD_WORK__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to work position actuator.
        /// </summary>
        public static string ___Move_to_work_position_actuator__ {
            get {
                return ResourceManager.GetString("___Move_to_work_position_actuator__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string ___Stop__ {
            get {
                return ResourceManager.GetString("___Stop__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP a.
        /// </summary>
        public static string ___STOP_a__ {
            get {
                return ResourceManager.GetString("___STOP_a__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP AND THINK.
        /// </summary>
        public static string ___STOP_AND_THINK__ {
            get {
                return ResourceManager.GetString("___STOP_AND_THINK__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOPDOUBLE.
        /// </summary>
        public static string ___STOPDOUBLE__ {
            get {
                return ResourceManager.GetString("___STOPDOUBLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string ___Work__ {
            get {
                return ResourceManager.GetString("___Work__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work position sensor.
        /// </summary>
        public static string ___Work_position_sensor__ {
            get {
                return ResourceManager.GetString("___Work_position_sensor__", resourceCulture);
            }
        }
    }
}
