<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3443" Id="{f2a4328a-b8aa-03e2-2bd5-fd6bfd729fab}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3443
VAR
	_io : EL3443_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{cfaa088a-517d-0d38-3b68-2a415355f805}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3443_Data]]></Declaration>
      <Get Name="Get" Id="{5de58be2-51ff-077b-1c84-28cc5563f74a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{e8a672a3-df13-08b5-136b-e11edda6362d}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{5e49a863-63a9-0dd6-2148-957edbe25580}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>