<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2596" Id="{c7ce0382-a06f-0c21-033a-7edddd5a38ea}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2596
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
	_io : EL2596_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{ee9ea180-50c2-0d51-3f13-08390b814ded}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2596_Data]]></Declaration>
      <Get Name="Get" Id="{2ae2f7f7-b56b-08d0-2934-dd7f30257dd8}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{5fce9226-d75a-0141-3c43-65800f8278cc}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{9ab9292c-dbfe-0ecb-277d-4f3cfbca2cfa}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>