<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="ST001_ProcessDataManager" Id="{37e7eeae-cd25-0b59-3f07-4f9672bf8a09}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ST001_ProcessDataManager EXTENDS TcoData.TcoDataExchange
VAR
    _data : ST001_ProcessData;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>