<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EXAMPLE_MAIN" Id="{2c5d3f02-495c-0bc3-10fa-11136d9736d0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM EXAMPLE_MAIN
VAR
	_context : ExampleCylinderContext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_context.Run();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>