<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1054" Id="{b40e8a16-2376-0fda-2ebb-d30723bef1cb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1054
VAR
	_io : EL1054_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{b5049b93-db96-03ac-128a-6c5a4a79068a}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1054_Data]]></Declaration>
      <Get Name="Get" Id="{7c0f2b95-573c-0a0d-3de5-5cd99e294b9d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{e4461aef-7825-0aa4-0b6e-7c4d5553a158}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{5eff3c18-2a6d-0a19-2fbb-995917aac1da}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>