<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3356" Id="{7add9fc4-fe7c-0568-28a9-495585b73a78}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3356
VAR
	_io : EL3356_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{6980b1fc-7032-06a2-38da-3bb1f29aa98e}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3356_Data]]></Declaration>
      <Get Name="Get" Id="{579d0e19-cac3-073e-0947-06ae63ab8777}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{febc1e57-9e43-00e4-2354-e8a93315ad3a}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{fe63f134-5c9e-0357-3d86-fc4f3078aba1}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>