<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3048" Id="{07ab9aec-8b6b-0cea-2f55-67c2947d4027}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3048
VAR
	_io : EL3xx8_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{1e407642-d228-0aad-3747-0e54840908fb}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3xx8_Data]]></Declaration>
      <Get Name="Get" Id="{2beeae3e-4305-039f-3822-48237f951689}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{a88294ad-fbaf-059b-22b5-9cbf75cf693c}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{1b27425f-4857-05ac-12f8-69136fba9dde}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>