<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3255" Id="{e486d387-27c8-074e-0b16-eeb703368e81}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3255
VAR
	_io : EL3xx5_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{8f347151-3c5f-0309-32c0-34275d4a7d66}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3xx5_Data]]></Declaration>
      <Get Name="Get" Id="{5ace10fd-e2e3-0c67-0cb6-8b2fb7788fb3}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{74bc412c-d49e-08f4-22c4-97231d8c9f94}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{a09dc6be-5a77-0540-27a7-2b1f7253dab2}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>