<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2878" Id="{ea797cfb-03ad-02d0-148d-8994e05511d3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2878
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2878_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{e2beb726-6e35-0db1-02ab-eccbb37f050b}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2878_Data]]></Declaration>
      <Get Name="Get" Id="{5db7d3b3-152d-0e46-2aba-bc871d4f0b19}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{3bcbd143-0380-073c-21d1-a81636d113f2}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{d02298a5-8fdd-07ca-1536-688a02e17ed1}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>