<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3423" Id="{b3723048-3de3-0707-0c95-a652b31bc350}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3423
VAR
	_io : EL3423_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAdsDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{141699b6-ee63-019d-323f-6b4ed5544ebd}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3423_Data]]></Declaration>
      <Get Name="Get" Id="{ca49f856-2b7e-0756-2b93-052696b76ad9}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{35d885b0-9fb6-035a-1050-e1ebdff668a5}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{8a198915-2c46-0975-273d-599bc8810ffb}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>