<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Person_Object" Id="{7dea4e2d-f024-0ba8-2c2e-ea35736e744d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Person_Object EXTENDS TcoCore.TcoObject
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Accept" Id="{44c4e924-54f1-0a50-03f2-592c994e5489}">
      <Declaration><![CDATA[METHOD Accept : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Refuse" Id="{3778f75f-808b-0091-0d24-ae374b268cd1}">
      <Declaration><![CDATA[METHOD Refuse : BOOL
VAR_INPUT
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="RequestForFavor" Id="{cf31844f-f21f-05a5-08eb-2ab3e61668a0}">
      <Declaration><![CDATA[METHOD PUBLIC RequestForFavor
VAR_INPUT
	inRequestedFavor	:	STRING;
	inReturnFavor		:	STRING;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>