<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Woltz_Object" Id="{210d7878-f3a8-0d74-1c18-c55600d21082}" SpecialFunc="None">
    <Declaration><![CDATA[//--
// <ObjectWithoutContextExampleDeclaration>
(*
		
			This is an example of self-confident object, that initiate its context by itself.

*)
FUNCTION_BLOCK Woltz_Object EXTENDS Person_Object
VAR
	//Horse owned by Jack Woltz.
	//https://godfather.fandom.com/wiki/Khartoum
	_Khartoum	: Horse_Object(THIS^);
END_VAR
//---------------------------------------------------------------------------
// </ObjectWithoutContextExampleDeclaration>
//--
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>