<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TcoSingleAxisDataTask" Id="{70b5fecb-d418-0a63-1b9f-b3b6f1baa87a}" SpecialFunc="None">
    <Declaration><![CDATA[(*~
	<docu>
		<summary>
			TcoSingleAxisDataTask task is a remote task  <see cref="PlcDocu.TcoCore.RemoteTask"/> with a paramater. 	
		</summary>	
		<param name="_identifier">The Identifier, ID  of an entity on which a CRUD operation should be executed</param>
		<remarks>Inxton is required for this feature to work</remarks>		
	</docu>	
~*)
FUNCTION_BLOCK TcoSingleAxisDataTask EXTENDS TcoCore.TcoRemoteTask
VAR
	(*~
	<docu>
		<summary>
			The Identifier, ID  of an entity on which a CRUD operation should be executed. 	
		</summary>						
	</docu>	
	~*)
    _identifier : STRING(255);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
    <Method Name="WithId" Id="{7131bbd6-0b83-0114-15d0-afa3b79f5b85}">
      <Declaration><![CDATA[
METHOD WithId : REFERENCE TO TcoSingleAxisDataTask
VAR_INPUT
	(*~
	<docu>
		<summary>
			The Identifier, ID  of an entity on which a CRUD operation should be executed. 	
		</summary>						
	</docu>	
	~*)
	inIdentifier : STRING(254);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^._identifier := inIdentifier;
WithId REF= THIS^;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>