<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1098" Id="{f054be23-768e-07ec-2f56-6cf51421b85a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1098
VAR
	_io : EL1xx8_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{02695b24-a382-01ca-35a0-02531134dded}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1xx8_Data]]></Declaration>
      <Get Name="Get" Id="{d83d31cf-4dec-06d4-3248-f0b7bebe2c20}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{dbbb16b4-de9a-02cb-0e80-72c0389136fe}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{5dbb9cad-be42-049f-16da-7053fc915791}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>