<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1008" Id="{c1a3e75e-5875-0559-077e-5b6483ea86af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1008
VAR
	_io : EL1xx8_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{a8869efd-7418-0758-2387-716e7a772f60}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1xx8_Data]]></Declaration>
      <Get Name="Get" Id="{a4a89d3c-eca8-066e-0377-cf16af365f2a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{1f28abc2-75cc-0765-20bf-07696982a777}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{7d7ec759-8c94-0de8-1e1b-7b8c1cafb61d}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>