<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1808" Id="{6b4f7620-935f-0051-0611-6de329f434af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1808
VAR
	_io : EL1xx8_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{7a7296ca-2938-044d-335b-de86b53e978a}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1xx8_Data]]></Declaration>
      <Get Name="Get" Id="{1e1ecf8c-811c-004e-0092-8681ced56b5e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{71aa7a32-85df-0034-0e88-42da49b30250}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{34b6d9f6-836e-0305-0cc9-4405539df2c4}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>