<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3413" Id="{69b112a8-50aa-0790-1859-0574338231fc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3413
VAR
	_io : EL3413_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{90fc9e8c-a50b-0ad6-39e1-a424beac33c6}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3413_Data]]></Declaration>
      <Get Name="Get" Id="{3216bb97-8019-07df-2504-82f9193f3c1b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{43c0707c-e70d-0c18-2d19-d033ef908a72}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{01219d49-c5a3-03a6-1444-bc715b42b660}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>