//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcOpen.Inxton.TcoMitsubishiRobotics.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcOpen.Inxton.TcoMitsubishiRobotics.Wpf.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High level error.
        /// </summary>
        public static string HighLevelError {
            get {
                return ResourceManager.GetString("HighLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key not in Auto.
        /// </summary>
        public static string KeyNotInAuto {
            get {
                return ResourceManager.GetString("KeyNotInAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low level error.
        /// </summary>
        public static string LowLevelError {
            get {
                return ResourceManager.GetString("LowLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motors On.
        /// </summary>
        public static string Motors_On {
            get {
                return ResourceManager.GetString("Motors On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motors Off.
        /// </summary>
        public static string MotorsOff {
            get {
                return ResourceManager.GetString("MotorsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is stoped.
        /// </summary>
        public static string ProgramIsNotRunning {
            get {
                return ResourceManager.GetString("ProgramIsNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is running.
        /// </summary>
        public static string ProgramIsRunning {
            get {
                return ResourceManager.GetString("ProgramIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Error!.
        /// </summary>
        public static string SafetyError {
            get {
                return ResourceManager.GetString("SafetyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Ok.
        /// </summary>
        public static string SafetyOk {
            get {
                return ResourceManager.GetString("SafetyOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning level error.
        /// </summary>
        public static string WarningLevelError {
            get {
                return ResourceManager.GetString("WarningLevelError", resourceCulture);
            }
        }
    }
}
