<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2522" Id="{c36636ae-d96a-0712-2956-a6cdc1663e4e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2522
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
	_io : EL2522_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{55d2c521-4432-068d-0c10-c5aed2ff8d7f}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2522_Data]]></Declaration>
      <Get Name="Get" Id="{c810faa5-59f7-098d-0735-9ad19451cbf7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{e7dc9f8e-f6ac-07b6-13c2-415419023dec}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{3c4e7495-c214-026a-29c5-9fb0680e0ab9}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>