<Project>
	<PropertyGroup>
		<MainScreenIndex>0</MainScreenIndex>
	</PropertyGroup>
	<ScreenMakerVersion>23.2</ScreenMakerVersion>
	<Type>FlexPendant</Type>
	<References />
	<Controller GUID="8f8bc920-d067-41ed-89f9-adc0be833312" Name="MTS3257" System="1200-108495" />
	<AssemblyInfo>
		<Title></Title>
		<Description>Code generated by ScreenMaker - Internal version 7.0.8730.594</Description>
		<Company></Company>
		<Product></Product>
		<Copyright></Copyright>
		<Trademark></Trademark>
		<Version>6.12.184</Version>
	</AssemblyInfo>
	<TpsViewInfo>
		<Caption>Visualization</Caption>
		<MenuImageName>tpu-Operator32.png</MenuImageName>
		<TaskbarImageName>tpu-Operator32.png</TaskbarImageName>
		<StartPanelLocation>1</StartPanelLocation>
		<ViewType>1</ViewType>
		<StartupType>1</StartupType>
	</TpsViewInfo>
	<ApplicationVariables>
		<Variable Name="allowTool" Value="False" ValueType="ABB.Robotics.Controllers.RapidDomain.Bool,ABB.Robotics.Controllers.PC" />
	</ApplicationVariables>
	<ItemGroup />
	<ItemGroup>
		<Compile Include=".\MainScreen.view">
			<Link>MainScreen.view</Link>
		</Compile>
	</ItemGroup>
	<StartVirtualFlexPendant>False</StartVirtualFlexPendant>
	<FPSDKInfo>
		<Version>6.10.1039</Version>
	</FPSDKInfo>
	<WidgetInfo />
</Project>