//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationProjectsConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationProjectsConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALARM OUTPUT.
        /// </summary>
        internal static string ___ALARM_OUTPUT__ {
            get {
                return ResourceManager.GetString("___ALARM_OUTPUT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMAT.
        /// </summary>
        internal static string ___AUTOMAT__ {
            get {
                return ResourceManager.GetString("___AUTOMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK PART REMOVAL FROM THE FIXTURE.
        /// </summary>
        internal static string ___CHECK_PART_REMOVAL_FROM_THE_FIXTURE__ {
            get {
                return ResourceManager.GetString("___CHECK_PART_REMOVAL_FROM_THE_FIXTURE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIVE.
        /// </summary>
        internal static string ___DRIVE__ {
            get {
                return ResourceManager.GetString("___DRIVE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUND.
        /// </summary>
        internal static string ___GROUND__ {
            get {
                return ResourceManager.GetString("___GROUND__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUND POSITION COMPLETED.
        /// </summary>
        internal static string ___GROUND_POSITION_COMPLETED__ {
            get {
                return ResourceManager.GetString("___GROUND_POSITION_COMPLETED__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground position completed; you can start automat sequence..
        /// </summary>
        internal static string ___Ground_position_completed__you_can_start_automat_sequence___ {
            get {
                return ResourceManager.GetString("___Ground_position_completed__you_can_start_automat_sequence___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD PART INTO FIXTURE.
        /// </summary>
        internal static string ___LOAD_PART_INTO_FIXTURE__ {
            get {
                return ResourceManager.GetString("___LOAD_PART_INTO_FIXTURE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUAL.
        /// </summary>
        internal static string ___MANUAL__ {
            get {
                return ResourceManager.GetString("___MANUAL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVING PRESS TO HOME POSITION.
        /// </summary>
        internal static string ___MOVING_PRESS_TO_HOME_POSITION__ {
            get {
                return ResourceManager.GetString("___MOVING_PRESS_TO_HOME_POSITION__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERATIONS COMPLETED.
        /// </summary>
        internal static string ___OPERATIONS_COMPLETED__ {
            get {
                return ResourceManager.GetString("___OPERATIONS_COMPLETED__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PART PRESENCE SENSOR.
        /// </summary>
        internal static string ___PART_PRESENCE_SENSOR__ {
            get {
                return ResourceManager.GetString("___PART_PRESENCE_SENSOR__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS IN BASE POSITION.
        /// </summary>
        internal static string ___PRESS_IN_BASE_POSITION__ {
            get {
                return ResourceManager.GetString("___PRESS_IN_BASE_POSITION__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS PISTON.
        /// </summary>
        internal static string ___PRESS_PISTON__ {
            get {
                return ResourceManager.GetString("___PRESS_PISTON__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS START BUTTON TO START OPERATIONS.
        /// </summary>
        internal static string ___PRESS_START_BUTTON_TO_START_OPERATIONS__ {
            get {
                return ResourceManager.GetString("___PRESS_START_BUTTON_TO_START_OPERATIONS__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESSING.
        /// </summary>
        internal static string ___PRESSING__ {
            get {
                return ResourceManager.GetString("___PRESSING__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE PART FROM THE FIXTURE.
        /// </summary>
        internal static string ___REMOVE_PART_FROM_THE_FIXTURE__ {
            get {
                return ResourceManager.GetString("___REMOVE_PART_FROM_THE_FIXTURE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove part from the fixture please.
        /// </summary>
        internal static string ___Remove_part_from_the_fixture_please__ {
            get {
                return ResourceManager.GetString("___Remove_part_from_the_fixture_please__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE DATA.
        /// </summary>
        internal static string ___SAVE_DATA__ {
            get {
                return ResourceManager.GetString("___SAVE_DATA__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START BUTTON.
        /// </summary>
        internal static string ___START_BUTTON__ {
            get {
                return ResourceManager.GetString("___START_BUTTON__", resourceCulture);
            }
        }
    }
}
