<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL5101" Id="{8491a08c-e246-0e92-32c9-75a9c424591a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL5101
VAR
	_io : EL5101_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAdsDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{70634c02-1c5a-00f1-394f-8fe5fecb7888}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL5101_Data]]></Declaration>
      <Get Name="Get" Id="{2e2297fa-10a3-0f28-2b8f-44e87405ca21}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{08fd0c56-30cc-07a2-058c-b5f9c493ea0b}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{7c1e9618-ecec-0fdb-309a-f2b6dc5281ce}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>