<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FuseModuleEL922x" Id="{e47d6a39-c379-42ae-ae60-e27562337e6d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FuseModuleEL922x
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_chn1Basic : IFuseChannelBasic;
	_chn2Basic : IFuseChannelBasic;
	_chn1Extended : IFuseChannelExtended;
	_chn2Extended : IFuseChannelExtended;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{a297a07f-4c09-4dae-9e3a-53ea4387aab8}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	chn1 : IFuseChannelBasic;
	chn2 : IFuseChannelBasic;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_chn1Basic := chn1;
__QUERYINTERFACE(_chn1Basic, _chn1Extended);
_chn2Basic := chn2;
__QUERYINTERFACE(_chn2Basic, _chn2Extended);]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FuseModuleEL922x">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FuseModuleEL922x.FB_init">
      <LineId Id="9" Count="2" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>