<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{6dac1541-74ba-49c0-be18-0d7d17fb8228}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	_tcoDrivesBeckhoffContext	:	TcoDrivesBeckhoffContext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>