<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="WrappedComponentExample" Id="{f443fe68-822c-036d-122a-3f9c9f3200c7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK WrappedComponentExample EXTENDS TcoCore.TcoComponent


VAR_OUTPUT
END_VAR
VAR
	_config:WrappedComponentExample_Config;
	_status:WrappedComponentExample_Status;
	_control:WrappedComponentExample_Control;
    _components:WrappedComponentsExample:= (Parent := THIS^);
	_throwTask:TcoCore.TcoTask(THIS^);
	_restoreTask:TcoCore.TcoTask(THIS^);

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Components" Id="{f2a63328-27cd-090c-37b1-a3ac64a01290}">
      <Declaration><![CDATA[PROPERTY Components : REFERENCE TO WrappedComponentsExample
]]></Declaration>
      <Get Name="Get" Id="{0c7dcdd5-c057-0b17-279d-c3102bfded2d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Components ref=_components;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Restore" Id="{e7fc1b31-1ecd-0bb4-3914-4bad4e42e83f}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Restores this instance to the Ready state. Can be called explicitly or from within one of the restore mechanisms.	
		</summary>			
	</docu>	
~*)
METHOD  Restore : ITcoRestorable


]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ServiceMode" Id="{a27c0e07-b8aa-070e-2ec6-644188aae071}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
		    Custom service (manual, maintenance) logic.
			This method must be implemented in derived class.
		</summary>			
	</docu>	
~*)
METHOD PROTECTED  ServiceMode
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>