<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="Station001ProcessData" Id="{73945634-36d0-4813-8f9d-01a731012014}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Station001ProcessData
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>