<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3002" Id="{95c5caca-d81f-0415-3c5d-4d58697c23f0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3002
VAR
	_io : EL3xx2_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{754d4e77-fb76-0127-23c9-ebca694f384d}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3xx2_Data]]></Declaration>
      <Get Name="Get" Id="{4e20f578-f3e3-0eb2-2f98-d1ed00c6ee27}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{b61ab933-ed6c-0c16-2b44-7f66dbf7bf11}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{2ca2807c-ebfa-0f57-022e-05209979e2d2}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>