<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3022" Id="{fd194cae-face-0f99-23ac-a88f572ee16d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3022
VAR
	_io : EL3xx2_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{03fa7585-9304-0b2d-1123-4e0df9c59df3}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3xx2_Data]]></Declaration>
      <Get Name="Get" Id="{8487a004-147c-0dea-2081-b61298dd0e2f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{96088c07-92c7-00f8-2883-0bad4dc3699a}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{284bd9b3-16fa-00eb-08ce-6e4ca159031a}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>