<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3612" Id="{02eb6413-1036-004a-29b4-ab09b84d237b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3612
VAR
	_io : EL36x2_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{4793406c-040e-0533-345e-434e433fa568}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL36x2_Data]]></Declaration>
      <Get Name="Get" Id="{c5af9bcc-9972-07b2-2be6-17b488a3c550}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{819d421f-94e7-002d-3b2d-e63eec09bdd2}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{9f26aaba-9446-03ff-3a9d-a2be2520cf67}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>