<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3602" Id="{f156213d-aa9f-0cda-2b34-95f69acf11be}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3602
VAR
	_io : EL36x2_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{9225f083-17ad-02c1-2640-0535f6ac1d1b}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL36x2_Data]]></Declaration>
      <Get Name="Get" Id="{7a7a02a6-4138-00c5-1749-2dedc4c7fc26}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{5a5e6d99-4f4f-0b70-22f2-dbe24c32e0d4}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{88719102-edab-0b5f-381a-aec463ea3e6c}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>