<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2034" Id="{ccdf7fb1-6280-0a59-08e8-0c889268391b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2034
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2034_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{041fb26d-4b6b-07c3-2e1f-6449b0cec665}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2034_Data]]></Declaration>
      <Get Name="Get" Id="{11a21d2f-d60c-0cd1-2b62-8248e27d7e15}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{f3c4aa76-06bb-0166-01b5-baa9938a40db}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{096e9518-0804-03a7-23b3-42ac9e0b9390}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>