<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1382" Id="{660d13a7-dc3d-070f-1b6f-64523eaeb86b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1382
VAR
	_io : EL1382_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{23388b71-1779-0cd5-0290-ba17cb8a9b73}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1382_Data]]></Declaration>
      <Get Name="Get" Id="{d5621659-edab-07cc-257b-a8fe7980f6f7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{6ae8e8e3-c621-05d6-2a37-a93c4a0fa027}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{1722d341-67d3-0e80-0b3a-527108af2f12}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>