<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL4018" Id="{b73ae929-a607-0847-3861-68e8e876292b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL4018
VAR
	_io : EL4xx8_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{ee0b5ae1-5823-0158-1dff-358db5f5cc48}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL4xx8_Data]]></Declaration>
      <Get Name="Get" Id="{cb4ddfec-6eea-087f-3941-1905463ba824}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{9ebe1272-0573-0a06-3d8d-75b5d6b0043a}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{867f06e3-bd2e-0b85-2627-1e2f8ac04759}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>