<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL4028" Id="{1b858de2-7da6-076e-08b9-207e915d495c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL4028
VAR
	_io : EL4xx8_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{a68d2f8e-36bd-02ce-338e-508449252f0a}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL4xx8_Data]]></Declaration>
      <Get Name="Get" Id="{bbbc3b88-25a1-08a9-30ad-4b2e7361fa8e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{3cc87d3f-0891-02f0-02f1-b33e9b8f4f44}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{0f7c2736-a8a6-0a5f-1d7f-0cfae0b37399}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>