<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL4031" Id="{667b1c07-9866-0169-2624-25728cd2baad}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL4031
VAR
	_io : EL4xx1_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{3566ffd6-3143-0397-24fd-22aae1377d13}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL4xx1_Data]]></Declaration>
      <Get Name="Get" Id="{f9da71bc-7159-0276-2a37-ce6d12a4da4a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{6c34aad5-c454-0b2e-2042-1a2fbb562e7a}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{64074e6c-6a58-0c05-3300-c1aab67f2cb1}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>