<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL4011" Id="{148c8f97-6491-0e15-1f65-53ef8a0997e0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL4011
VAR
	_io : EL4xx1_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{420c9608-697e-0032-218e-23b7d811fe88}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL4xx1_Data]]></Declaration>
      <Get Name="Get" Id="{4be6a96f-6335-0e41-2e9d-9b400c56201f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{641f1b1f-6dd2-07df-2489-ef524a565ae8}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{236511b6-8b6c-0fc4-20e3-e8c08ba0585f}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>