<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Horse_Object" Id="{318d333c-8793-0528-10f0-90d7a7341f0d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Horse_Object EXTENDS TcoCore.TcoObject
VAR
	_price	: LREAL;	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Price" Id="{e3ea7672-3134-0a22-002f-336efed6f2c1}">
      <Declaration><![CDATA[PROPERTY Price : LREAL]]></Declaration>
      <Get Name="Get" Id="{60034efa-7b3c-067d-33aa-263f0b37071f}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Price := _price;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{2a4ab36a-6675-009d-23bc-d597f5ec2ca8}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[_price := Price;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>