//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainPlcConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainPlcConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMAT.
        /// </summary>
        public static string ___AUTOMAT__ {
            get {
                return ResourceManager.GetString("___AUTOMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMAT ALL.
        /// </summary>
        public static string ___AUTOMAT_ALL__ {
            get {
                return ResourceManager.GetString("___AUTOMAT_ALL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings the device into basic position..
        /// </summary>
        public static string ___Brings_the_device_into_basic_position___ {
            get {
                return ResourceManager.GetString("___Brings_the_device_into_basic_position___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string ___Carrier__ {
            get {
                return ResourceManager.GetString("___Carrier__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean loop time.
        /// </summary>
        public static string ___Clean_loop_time__ {
            get {
                return ResourceManager.GetString("___Clean_loop_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ___Created__ {
            get {
                return ResourceManager.GetString("___Created__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle time.
        /// </summary>
        public static string ___Cycle_time__ {
            get {
                return ResourceManager.GetString("___Cycle_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string ___Empty__ {
            get {
                return ResourceManager.GetString("___Empty__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity header.
        /// </summary>
        public static string ___Entity_header__ {
            get {
                return ResourceManager.GetString("___Entity_header__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUND.
        /// </summary>
        public static string ___GROUND__ {
            get {
                return ResourceManager.GetString("___GROUND__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUND ALL.
        /// </summary>
        public static string ___GROUND_ALL__ {
            get {
                return ResourceManager.GetString("___GROUND_ALL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ___ID__ {
            get {
                return ResourceManager.GetString("___ID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDLE.
        /// </summary>
        public static string ___IDLE__ {
            get {
                return ResourceManager.GetString("___IDLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Rework Name.
        /// </summary>
        public static string ___Last_Rework_Name__ {
            get {
                return ResourceManager.GetString("___Last_Rework_Name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last station.
        /// </summary>
        public static string ___Last_station__ {
            get {
                return ResourceManager.GetString("___Last_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUAL.
        /// </summary>
        public static string ___MANUAL__ {
            get {
                return ResourceManager.GetString("___MANUAL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string ___Master__ {
            get {
                return ResourceManager.GetString("___Master__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string ___Modified__ {
            get {
                return ResourceManager.GetString("___Modified__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next on Failed.
        /// </summary>
        public static string ___Next_on_Failed__ {
            get {
                return ResourceManager.GetString("___Next_on_Failed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next on Passed.
        /// </summary>
        public static string ___Next_on_Passed__ {
            get {
                return ResourceManager.GetString("___Next_on_Passed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next station.
        /// </summary>
        public static string ___Next_station__ {
            get {
                return ResourceManager.GetString("___Next_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation ended.
        /// </summary>
        public static string ___Operation_ended__ {
            get {
                return ResourceManager.GetString("___Operation_ended__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation started.
        /// </summary>
        public static string ___Operation_started__ {
            get {
                return ResourceManager.GetString("___Operation_started__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations opened.
        /// </summary>
        public static string ___Operations_opened__ {
            get {
                return ResourceManager.GetString("___Operations_opened__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string ___Operator__ {
            get {
                return ResourceManager.GetString("___Operator__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process data not selected.
        /// </summary>
        public static string ___Process_data_not_selected__ {
            get {
                return ResourceManager.GetString("___Process_data_not_selected__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY TO START.
        /// </summary>
        public static string ___READY_TO_START__ {
            get {
                return ResourceManager.GetString("___READY_TO_START__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        public static string ___Recipe__ {
            get {
                return ResourceManager.GetString("___Recipe__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe created.
        /// </summary>
        public static string ___Recipe_created__ {
            get {
                return ResourceManager.GetString("___Recipe_created__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe modified.
        /// </summary>
        public static string ___Recipe_modified__ {
            get {
                return ResourceManager.GetString("___Recipe_modified__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ___Reset__ {
            get {
                return ResourceManager.GetString("___Reset__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ___Results__ {
            get {
                return ResourceManager.GetString("___Results__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rework Count.
        /// </summary>
        public static string ___Rework_Count__ {
            get {
                return ResourceManager.GetString("___Rework_Count__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reworked.
        /// </summary>
        public static string ___Reworked__ {
            get {
                return ResourceManager.GetString("___Reworked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start manual/Service mode.
        /// </summary>
        public static string ___Start_manual_Service_mode__ {
            get {
                return ResourceManager.GetString("___Start_manual_Service_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts automatic sequence. Before start you need to perform grounding sequence..
        /// </summary>
        public static string ___Starts_automatic_sequence__Before_start_you_need_to_perform_grounding_sequence___ {
            get {
                return ResourceManager.GetString("___Starts_automatic_sequence__Before_start_you_need_to_perform_grounding_sequence" +
                        "___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to load default settings?.
        /// </summary>
        public static string ___Would_you_like_to_load_default_settings___ {
            get {
                return ResourceManager.GetString("___Would_you_like_to_load_default_settings___", resourceCulture);
            }
        }
    }
}
