<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3446" Id="{1e9b08da-1d8e-0a37-28b6-e053f5a72b63}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3446
VAR
	_io : EL3446_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAdsDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{23267630-9772-035d-2eb0-799adec85a74}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3446_Data]]></Declaration>
      <Get Name="Get" Id="{8fbf8e4d-f8c4-01b6-194b-d08d577b8aa7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{9f3ff598-5a79-0060-2732-25a6d978fcb7}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{23755f62-733f-0a64-281d-45c3afdb0329}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>