<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="TcoContextBuilder" Id="{11fcb5e1-103e-0f9c-0257-e5ca5502dbf8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcoContextBuilder IMPLEMENTS ITcoContexBuilder
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Build" Id="{7331aaf2-9e6a-0ef8-0818-7d0782751f80}">
      <Declaration><![CDATA[METHOD Build : ITcoContexBuilder
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{e931dbe5-856c-06ff-272d-79b39b5e89f4}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)	
	Context : ITcoContext; 
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="WithLogger" Id="{1658510a-bf2a-04c6-0ec2-27e989db34d1}">
      <Declaration><![CDATA[METHOD WithLogger : ITcoContexBuilder
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>