<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="PRG_MAIN" Id="{cb90af5d-f0ec-4337-9183-9e58e9e11014}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_MAIN
VAR
	_pneuMan : ST_01_Context;
	_donCorleone : VitoCorleone_Context;
	//Self-confident object, that initiate its context BY itself.	
	_jackWaltz	:	Woltz_Object(_jackWaltz);
//	_donCorleoneTaskExt : VitoCorleone_ContextTaskExt;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_pneuMan.Run();
_donCorleone.Run();

//_donCorleoneTaskExt.Run();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>