//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlcHammerConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlcHammerConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position.
        /// </summary>
        public static string ___Current_position__ {
            get {
                return ResourceManager.GetString("___Current_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move absolute.
        /// </summary>
        public static string ___Move_absolute__ {
            get {
                return ResourceManager.GetString("___Move_absolute__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE HOME.
        /// </summary>
        public static string ___MOVE_HOME__ {
            get {
                return ResourceManager.GetString("___MOVE_HOME__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE TO WORK.
        /// </summary>
        public static string ___MOVE_TO_WORK__ {
            get {
                return ResourceManager.GetString("___MOVE_TO_WORK__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the drive to absolute position given by parameter &apos;Target Position&apos;.
        /// </summary>
        public static string ___Moves_the_drive_to_absolute_position_given_by_parameter__Target_Position___ {
            get {
                return ResourceManager.GetString("___Moves_the_drive_to_absolute_position_given_by_parameter__Target_Position___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        public static string ___STOP__ {
            get {
                return ResourceManager.GetString("___STOP__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target position.
        /// </summary>
        public static string ___Target_position__ {
            get {
                return ResourceManager.GetString("___Target_position__", resourceCulture);
            }
        }
    }
}
