<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="TaskExecution" Id="{4822b8a3-73e8-03f9-109e-c2dfb282b463}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TaskExecution  EXTENDS TcoCore.TcoContext
VAR
	FastTask : FastCounter(THIS^);
	SlowTask : SlowCounter(THIS^);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Use main method instead]]></ST>
    </Implementation>
    <Method Name="Main" Id="{81068e5b-2c3f-096f-298b-5a1ef745c23a}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Main method of the TcoContext. This is the entry point of any control logic that belongs to this context. 
			The call of this method is ensured by calling the <c>InstanceName.Run()</c> method, and it must not be called explicitly.
			This method is abstract, and it must be overridden in derived block.
		</summary>
	</docu>
~*)
METHOD PROTECTED  Main]]></Declaration>
      <Implementation>
        <ST><![CDATA[SlowTask();
FastTask();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>