<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="CoordinatesAreEqual" Id="{e35435aa-cd0e-00fc-27d0-d1fbc833f889}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CoordinatesAreEqual : bool
VAR_INPUT
	Coordinates1 : TcoRoboticsCoordinates;
	Coordinates2 : TcoRoboticsCoordinates;
	EpsilonX : REAL; 
	EpsilonY : REAL; 
	EpsilonZ : REAL; 
	EpsilonRx : REAL; 
	EpsilonRy : REAL; 
	EpsilonRz : REAL; 
END_VAR

VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CoordinatesAreEqual :=	IsNearlyEqual(Coordinates1.X,Coordinates2.X,EpsilonX)  AND
						IsNearlyEqual(Coordinates1.Y,Coordinates2.Y,EpsilonY)  AND
						IsNearlyEqual(Coordinates1.Z,Coordinates2.Z,EpsilonZ)  AND
						IsNearlyEqual(Coordinates1.Rx,Coordinates2.Rx,EpsilonRx)  AND
						IsNearlyEqual(Coordinates1.Ry,Coordinates2.Ry,EpsilonRy)  AND
						IsNearlyEqual(Coordinates1.Rz,Coordinates2.Rz,EpsilonRz);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>