<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL4124" Id="{fc3b5d92-f271-08b4-2443-0406d2a8826d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL4124
VAR
	_io : EL4xx4_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{71da850c-3a25-06b3-0b11-4eae728909aa}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL4xx4_Data]]></Declaration>
      <Get Name="Get" Id="{1b5336eb-6eb8-0c14-2080-e841009e8654}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{4f9a32cd-086a-0a8e-1c31-cbf8a3c87f0e}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{7c5db780-b9c1-0df2-28ca-1c07f1303290}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>