<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TcoDataTask" Id="{7211395c-b0ba-0bf9-25be-0541f79b5876}" SpecialFunc="None">
    <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Data task is a remote task  <see cref="PlcDocu.TcoCore.RemoteTask"/> with a paramater. 	
		</summary>	
		<param name="_identifier">The Identifier, ID  of an entity on which a CRUD operation should be executed</param>
		<remarks>Inxton is required for this feature to work</remarks>		
	</docu>	
~*)
FUNCTION_BLOCK TcoDataTask EXTENDS TcoCore.TcoRemoteTask
VAR
	(*~
	<docu>
		<summary>
			The Identifier, ID  of an entity on which a CRUD operation should be executed. 	
		</summary>						
	</docu>	
	~*)
    _identifier : STRING(255);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
    <Method Name="WithId" Id="{73957c41-6f21-008e-2bf1-1954b1beab89}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Executes CRUD operation on data entry with given identifier. 	
		</summary>			
		<remarks>Inxton is required for this feature to work</remarks>		
	</docu>	
~*)
METHOD WithId : REFERENCE TO TcoDataTask
VAR_INPUT
	(*~
	<docu>
		<summary>
			The Identifier, ID  of an entity on which a CRUD operation should be executed. 	
		</summary>						
	</docu>	
	~*)
	inIdentifier : STRING(254);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^._identifier := inIdentifier;
WithId REF= THIS^;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>