<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TcoDataTask" Id="{fba012ea-068f-05dc-1582-4c71451ec071}" SpecialFunc="None">
    <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Data task is a remote task  <see cref="PlcDocu.TcoCore.RemoteTask"/> with a paramater. 	
		</summary>	
		<param name="_identifier">The Identifier, ID  of an entity on which a CRUD operation should be executed</param>
		<remarks>Inxton is required for this feature to work</remarks>		
	</docu>	
~*)
FUNCTION_BLOCK TcoDataTask EXTENDS TcoCore.TcoRemoteTask
VAR
	(*~
	<docu>
		<summary>
			The Identifier, ID  of an entity on which a CRUD operation should be executed. 	
		</summary>						
	</docu>	
	~*)
    _identifier : STRING(255);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{03c5aeaf-9a88-0e65-2886-43aec8e1a787}">
      <Declaration><![CDATA[METHOD PUBLIC FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	ParentObject : TcoCore.ITcoObject;	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="WithId" Id="{25a8d4cd-cb14-0b25-0924-5b000f738181}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Executes CRUD operation on data entry with given identifier. 	
		</summary>			
		<remarks>Inxton is required for this feature to work</remarks>		
	</docu>	
~*)
METHOD WithId : REFERENCE TO TcoDataTask
VAR_INPUT
	(*~
	<docu>
		<summary>
			The Identifier, ID  of an entity on which a CRUD operation should be executed. 	
		</summary>						
	</docu>	
	~*)
	inIdentifier : STRING(254);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^._identifier := inIdentifier;
WithId REF= THIS^;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="TcoDataTask">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="TcoDataTask.FB_init">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="TcoDataTask.WithId">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>