<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL6022" Id="{ec567efb-6342-0207-382e-51839bb506b4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL6022
VAR
	_io : EL6022_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{9e41126c-cdd8-0e72-1b09-0b020343b094}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL6022_Data]]></Declaration>
      <Get Name="Get" Id="{1f718637-4e4d-0e8c-0835-fbc9bf1701ad}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{c3a99665-5973-0263-2ac5-468b9cc6a8d5}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{e66da85b-6160-0106-3812-89294848a75e}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>