<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL6070" Id="{04c1e157-8f0f-0181-1d04-19821131d234}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL6070
VAR
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>