<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL6601" Id="{d30ef104-5d01-04ac-1565-d0f451498cf9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL6601
VAR
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>