<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL6614" Id="{311c3909-3d81-0f08-206f-35a5e07b9f03}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL6614
VAR
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>