//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoIoConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoIoConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Link state.
        /// </summary>
        public static string ___Actual_Link_state__ {
            get {
                return ResourceManager.GetString("___Actual_Link_state__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual state.
        /// </summary>
        public static string ___Actual_state__ {
            get {
                return ResourceManager.GetString("___Actual_state__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads address information is not defined!.
        /// </summary>
        public static string ___Ads_address_information_is_not_defined___ {
            get {
                return ResourceManager.GetString("___Ads_address_information_is_not_defined___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT least one AlarmCR got a diagnosis alarm!.
        /// </summary>
        public static string ___AT_least_one_AlarmCR_got_a_diagnosis_alarm___ {
            get {
                return ResourceManager.GetString("___AT_least_one_AlarmCR_got_a_diagnosis_alarm___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one InputCR is invalid!.
        /// </summary>
        public static string ___At_least_one_InputCR_is_invalid___ {
            get {
                return ResourceManager.GetString("___At_least_one_InputCR_is_invalid___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT least one InputCR is invalid, provider in stop OR problemindicator is set!.
        /// </summary>
        public static string ___AT_least_one_InputCR_is_invalid__provider_in_stop_OR_problemindicator_is_set___ {
            get {
                return ResourceManager.GetString("___AT_least_one_InputCR_is_invalid__provider_in_stop_OR_problemindicator_is_set__" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one InputCR Problemindicator is set!.
        /// </summary>
        public static string ___At_least_one_InputCR_Problemindicator_is_set___ {
            get {
                return ResourceManager.GetString("___At_least_one_InputCR_Problemindicator_is_set___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT least one InputCR Provider is in stop!.
        /// </summary>
        public static string ___AT_least_one_InputCR_Provider_is_in_stop___ {
            get {
                return ResourceManager.GetString("___AT_least_one_InputCR_Provider_is_in_stop___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT least one OutputCR is invalid!.
        /// </summary>
        public static string ___AT_least_one_OutputCR_is_invalid___ {
            get {
                return ResourceManager.GetString("___AT_least_one_OutputCR_is_invalid___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one OutputCR is invalid, provider in stop or problemindicator is set!.
        /// </summary>
        public static string ___At_least_one_OutputCR_is_invalid__provider_in_stop_or_problemindicator_is_set___ {
            get {
                return ResourceManager.GetString("___At_least_one_OutputCR_is_invalid__provider_in_stop_or_problemindicator_is_set_" +
                        "__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT least one OutputCR Problemindicator is set!.
        /// </summary>
        public static string ___AT_least_one_OutputCR_Problemindicator_is_set___ {
            get {
                return ResourceManager.GetString("___AT_least_one_OutputCR_Problemindicator_is_set___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one OutputCR Provider is in stop!.
        /// </summary>
        public static string ___At_least_one_OutputCR_Provider_is_in_stop___ {
            get {
                return ResourceManager.GetString("___At_least_one_OutputCR_Provider_is_in_stop___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change State.
        /// </summary>
        public static string ___Change_State__ {
            get {
                return ResourceManager.GetString("___Change_State__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datahold error!.
        /// </summary>
        public static string ___Datahold_error___ {
            get {
                return ResourceManager.GetString("___Datahold_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCP set was NOT successful!.
        /// </summary>
        public static string ___DCP_set_was_NOT_successful___ {
            get {
                return ResourceManager.GetString("___DCP_set_was_NOT_successful___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device NOT found!.
        /// </summary>
        public static string ___Device_NOT_found___ {
            get {
                return ResourceManager.GetString("___Device_NOT_found___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECAT Communication Ok.
        /// </summary>
        public static string ___ECAT_Communication_Ok__ {
            get {
                return ResourceManager.GetString("___ECAT_Communication_Ok__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecat slave state.
        /// </summary>
        public static string ___Ecat_slave_state__ {
            get {
                return ResourceManager.GetString("___Ecat_slave_state__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Time.
        /// </summary>
        public static string ___Error_Time__ {
            get {
                return ResourceManager.GetString("___Error_Time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EtherCAT gateway: WC-State OF cyclic EtherCAT frame is 1!.
        /// </summary>
        public static string ___EtherCAT_gateway__WC_State_OF_cyclic_EtherCAT_frame_is_1___ {
            get {
                return ResourceManager.GetString("___EtherCAT_gateway__WC_State_OF_cyclic_EtherCAT_frame_is_1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EtherCat masters Ams Net Id.
        /// </summary>
        public static string ___EtherCat_masters_Ams_Net_Id__ {
            get {
                return ResourceManager.GetString("___EtherCat_masters_Ams_Net_Id__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOC-AR is established!.
        /// </summary>
        public static string ___IOC_AR_is_established___ {
            get {
                return ResourceManager.GetString("___IOC_AR_is_established___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOC-AR is established but module difference!.
        /// </summary>
        public static string ___IOC_AR_is_established_but_module_difference___ {
            get {
                return ResourceManager.GetString("___IOC_AR_is_established_but_module_difference___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOC-AR is established but no application ready!.
        /// </summary>
        public static string ___IOC_AR_is_established_but_no_application_ready___ {
            get {
                return ResourceManager.GetString("___IOC_AR_is_established_but_no_application_ready___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOC-AR is not established!.
        /// </summary>
        public static string ___IOC_AR_is_not_established___ {
            get {
                return ResourceManager.GetString("___IOC_AR_is_not_established___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP conflict!.
        /// </summary>
        public static string ___IP_conflict___ {
            get {
                return ResourceManager.GetString("___IP_conflict___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP could NOT be set!.
        /// </summary>
        public static string ___IP_could_NOT_be_set___ {
            get {
                return ResourceManager.GetString("___IP_could_NOT_be_set___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profinet controller has a link error!.
        /// </summary>
        public static string ___Profinet_controller_has_a_link_error___ {
            get {
                return ResourceManager.GetString("___Profinet_controller_has_a_link_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profinet device state machine is in boot mode!.
        /// </summary>
        public static string ___Profinet_device_state_machine_is_in_boot_mode___ {
            get {
                return ResourceManager.GetString("___Profinet_device_state_machine_is_in_boot_mode___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required state.
        /// </summary>
        public static string ___Required_state__ {
            get {
                return ResourceManager.GetString("___Required_state__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string ___Restore__ {
            get {
                return ResourceManager.GetString("___Restore__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTC3: Sync mode could not be initiated!.
        /// </summary>
        public static string ___RTC3__Sync_mode_could_not_be_initiated___ {
            get {
                return ResourceManager.GetString("___RTC3__Sync_mode_could_not_be_initiated___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State check Time(Period).
        /// </summary>
        public static string ___State_check_Time_Period___ {
            get {
                return ResourceManager.GetString("___State_check_Time_Period___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aliasname is not unique!.
        /// </summary>
        public static string ___The_aliasname_is_not_unique___ {
            get {
                return ResourceManager.GetString("___The_aliasname_is_not_unique___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The automatic name assignement is not possible - wrong device TYPE!.
        /// </summary>
        public static string ___The_automatic_name_assignement_is_not_possible___wrong_device_TYPE___ {
            get {
                return ResourceManager.GetString("___The_automatic_name_assignement_is_not_possible___wrong_device_TYPE___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stationname is not unique!.
        /// </summary>
        public static string ___The_stationname_is_not_unique___ {
            get {
                return ResourceManager.GetString("___The_stationname_is_not_unique___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected state: .
        /// </summary>
        public static string ___Unexpected_state____ {
            get {
                return ResourceManager.GetString("___Unexpected_state____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchdog error!.
        /// </summary>
        public static string ___Watchdog_error___ {
            get {
                return ResourceManager.GetString("___Watchdog_error___", resourceCulture);
            }
        }
    }
}
