<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="TcoContext_Waveform" Id="{76c1cbb5-02cf-02d0-2e44-70ab9bc25555}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcoContext_Waveform EXTENDS TcoContextTest
VAR
	_TcoObject_Waveform		:	TcoObject_Waveform(THIS^);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Main" Id="{229b1708-b47b-0826-0b45-44b4bc509029}">
      <Declaration><![CDATA[METHOD PROTECTED  Main]]></Declaration>
      <Implementation>
        <ST><![CDATA[_TcoObject_Waveform();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>