<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2024" Id="{e608f0f1-b53b-0701-2b2d-0d5bd2452e45}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2024
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2xx4_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{109fc22b-3fe4-0771-120e-44dd8c8ead94}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2xx4_Data]]></Declaration>
      <Get Name="Get" Id="{07570e0d-a92f-02af-1fa7-1ab295464f24}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{3fe43c3f-7120-0d11-20d1-3f6dd876ca06}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{da747640-b2e1-0841-2171-8595d547f4fc}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>