<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2004" Id="{974b32bf-21a7-0587-2ee5-7bf79cdc3bbe}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2004
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2xx4_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{81a7df0b-a4df-0c3d-0d10-3f2ced3b8c49}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2xx4_Data]]></Declaration>
      <Get Name="Get" Id="{8c9c94a4-edf9-0322-2cb7-8aadfd8eaaf8}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{f0b412f5-a339-0228-0837-c951edae2d6b}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{15d121a6-87f8-08cb-1148-417b76a3312d}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>