<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2124" Id="{53152100-24b2-0334-1b29-6056c5c8afec}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2124
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2xx4_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{33ec2263-788d-0396-1512-58cf3f7e1c9d}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2xx4_Data]]></Declaration>
      <Get Name="Get" Id="{5a2e64af-7650-0b38-0db5-f98a863e804f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{2e770bb6-9321-013c-0dbe-dd9b70bf7c3a}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{98c1ca99-34ad-03cf-262e-a35b1244f995}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>