<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="ConnectSequences" Id="{42a4829e-b662-0a53-329a-d62d67b66a95}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ConnectSequences EXTENDS TcoCore.TcoContext
VAR
	Automat : AutomatSequence(THIS^, eRestoreMode.AutoRestoreMembers);
	Ground : GroundSequence(THIS^, eRestoreMode.AutoRestoreMembers);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Use main method]]></ST>
    </Implementation>
    <Method Name="Main" Id="{0260a0b5-6e18-0e05-3534-d1036e2d1887}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Main method of the TcoContext. This is the entry point of any control logic that belongs to this context. 
			The call of this method is ensured by calling the <c>InstanceName.Run()</c> method, and it must not be called explicitly.
			This method is abstract, and it must be overridden in derived block.
		</summary>
	</docu>
~*)
METHOD PROTECTED  Main]]></Declaration>
      <Implementation>
        <ST><![CDATA[Ground.Run();

IF  Ground.GroundDone THEN
	Automat.Run();
END_IF ]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>