<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="my_sequencer" Id="{be4c83b2-b2a5-454b-ae90-724de0f675a4}" SpecialFunc="None">
    <Declaration>FUNCTION_BLOCK my_sequencer EXTENDS TcoCore.TcoSequencer</Declaration>
    <Implementation>
      <ST />
    </Implementation>
    <Method Name="Main" Id="{3573eb9e-30ac-4277-a062-43ffa84965ff}">
      <Declaration>METHOD PROTECTED Main : BOOL</Declaration>
      <Implementation>
        <ST>IF TRUE THEN; END_IF;</ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>