<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="my_sequencer" Id="{0594bfab-282c-45ac-ad0e-7635b4fdcdec}" SpecialFunc="None">
    <Declaration>FUNCTION_BLOCK my_sequencer EXTENDS TcoCore.TcoSequencer</Declaration>
    <Implementation>
      <ST />
    </Implementation>
    <Method Name="Main" Id="{991e11eb-86d2-48f6-a01b-0480ae608e5f}">
      <Declaration>METHOD PROTECTED Main : BOOL</Declaration>
      <Implementation>
        <ST>IF TRUE THEN; END_IF;</ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>