<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="StrucuredContext" Id="{cdced5f6-42a4-0b44-152c-1ab0e5e1a0ae}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK StrucuredContext EXTENDS TcoCore.TcoContext
VAR
    _structuredData : StructuredData := (Parent := THIS^);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Main" Id="{b2a35672-e371-0cab-27c6-b3230f63e23f}">
      <Declaration><![CDATA[(*~
    <docu>
        <summary>
            Main method of the TcoContext. This is the entry point of any control logic that belongs to this context.
            The call of this method is ensured by calling the <c>InstanceName.Run()</c> method, and it must not be called explicitly.
            This method is abstract, and it must be overridden in derived block.
        </summary>
    </docu>
~*)
METHOD PROTECTED Main]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>