<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3433" Id="{f1b94e97-55db-0d1b-0df6-f64e7dbfc90f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3433
VAR
	_io : EL3433_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{21226375-7735-01af-0cb6-2bc285231e6a}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3433_Data]]></Declaration>
      <Get Name="Get" Id="{7731d2fe-02cf-0068-21f6-fc75a7b23325}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{2fd0fe1a-12e1-0724-32cd-d51957a47245}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{8c141354-c09e-0e6c-1a7e-a7a4d3bc6002}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>