<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1512" Id="{8ac0c417-629f-0746-1984-7fe01d85ce68}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1512
VAR
	_io : EL1512_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{21f49c6a-45ef-0a24-0527-f57c167bafc5}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1512_Data]]></Declaration>
      <Get Name="Get" Id="{eaebc8df-0571-03dc-3ee5-2d8cd2e52a59}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{81a43219-6773-0953-10c9-32481fa73fc0}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{5ef978a2-ea56-0a69-2e33-b853f7f6231e}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>