<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL6021" Id="{594de927-51a2-0ada-1f91-52e57d8787de}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL6021
VAR
	_io : EL6021_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{7639b71c-19bc-07a3-2919-dcbd2ead2658}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL6021_Data]]></Declaration>
      <Get Name="Get" Id="{6962a2ef-9c13-0bd4-1d5f-740e6514d385}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{81263b8b-e416-0bfd-2d6c-33e4c0a30a60}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{6ea4da4d-ce3f-07d2-26e9-46dfd1308537}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>