<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="SampleComponentTests" Id="{b17ec03a-36c6-052c-046e-9fa4ab19268d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SampleComponentTests EXTENDS _internals_TcoContext
VAR
	_sut : IntegrationProjects.SampleComponent(THIS^);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <Method Name="AddTwoNumbersTest" Id="{6e4ddacd-63fc-0edb-2f1c-cda19003747e}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD INTERNAL AddTwoNumbersTest : INT
VAR_INPUT
	NumberOne : INT;
	NumberTwo : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[AddTwoNumbersTest := _sut.AddTwoNumbers(NumberOne, NumberTwo);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Main" Id="{cda4120d-522d-0a47-3c12-3ab2d43f1c71}">
      <Declaration><![CDATA[METHOD PROTECTED Main
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="WaitForModuloTest" Id="{ac76245a-17a9-06d1-3210-215ea4badadd}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD INTERNAL WaitForModuloTest : BOOL
VAR_INPUT
	Modulo : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[WaitForModuloTest := _sut.WaitForModulo(Modulo);
	]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>