<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="AKid_Object" Id="{0da65770-c59b-0cdc-1561-1886703cb24f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AKid_Object EXTENDS TcoCore.TcoObject
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>