<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="AKid_Object" Id="{e294d120-cf43-03a3-359f-c3cc9e9ae641}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AKid_Object EXTENDS TcoCore.TcoObject
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>