<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SomeTestPositions" Id="{00d8b7c4-ef7f-03f9-2c3e-06b46cf10665}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SomeTestPositions EXTENDS TcoDrivesBeckhoff.TcoSingleAxisPositionsRootContainer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    {attribute addProperty Name "<#Pick Position#>"}
    PickPosition : TcoDrivesBeckhoff.TcoMultiAxisMoveParam;
    {attribute addProperty Name "<#Place  Position#>"}
    PlacePosition : TcoDrivesBeckhoff.TcoMultiAxisMoveParam;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>