<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SomeTestMultiPositions" Id="{8273acfc-9b9e-0909-3854-4c84a6bea50d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SomeTestMultiPositions EXTENDS TcoDrivesBeckhoff.TcoMultiAxisPositionsRootContainer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    {attribute addProperty Name "<#Pick Position#>"}
    PickPosition : TcoDrivesBeckhoff.TcoMultiAxisMoveParam;
    {attribute addProperty Name "<#Place  Position#>"}
    PlacePosition : TcoDrivesBeckhoff.TcoMultiAxisMoveParam;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="PickPos" Id="{9afc3efe-977f-0cfa-2091-6b82330b36d7}">
      <Declaration><![CDATA[PROPERTY PUBLIC PickPos : REFERENCE TO TcoDrivesBeckhoff.TcoMultiAxisMoveParam;]]></Declaration>
      <Get Name="Get" Id="{54fd2e36-1768-0b24-3aaa-aa9fb0032d69}">
        <Declaration><![CDATA[VAR
END_VAR]]></Declaration>
        <Implementation>
          <ST><![CDATA[PickPos REF= PickPosition;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="PlacePos" Id="{48a58c59-a745-03be-305d-ea8c1e8e9873}">
      <Declaration><![CDATA[PROPERTY PUBLIC PlacePos : REFERENCE TO TcoDrivesBeckhoff.TcoMultiAxisMoveParam;]]></Declaration>
      <Get Name="Get" Id="{51fcacf0-79b0-0952-0548-14f5f353edb9}">
        <Declaration><![CDATA[VAR
END_VAR]]></Declaration>
        <Implementation>
          <ST><![CDATA[PlacePos REF= PlacePosition;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>