//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoPneumaticsConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoPneumaticsConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ___Home__ {
            get {
                return ResourceManager.GetString("___Home__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home and work position sensors are both active. Check the position of sensors!.
        /// </summary>
        public static string ___Home_and_work_position_sensors_are_both_active__Check_the_position_of_sensors___ {
            get {
                return ResourceManager.GetString("___Home_and_work_position_sensors_are_both_active__Check_the_position_of_sensors_" +
                        "__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home position sensor.
        /// </summary>
        public static string ___Home_position_sensor__ {
            get {
                return ResourceManager.GetString("___Home_position_sensor__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home sensor signal.
        /// </summary>
        public static string ___Home_sensor_signal__ {
            get {
                return ResourceManager.GetString("___Home_sensor_signal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE HOME.
        /// </summary>
        public static string ___MOVE_HOME__ {
            get {
                return ResourceManager.GetString("___MOVE_HOME__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to home position actuator.
        /// </summary>
        public static string ___Move_to_home_position_actuator__ {
            get {
                return ResourceManager.GetString("___Move_to_home_position_actuator__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to home position signal.
        /// </summary>
        public static string ___Move_to_home_position_signal__ {
            get {
                return ResourceManager.GetString("___Move_to_home_position_signal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE TO WORK.
        /// </summary>
        public static string ___MOVE_TO_WORK__ {
            get {
                return ResourceManager.GetString("___MOVE_TO_WORK__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to work position actuator.
        /// </summary>
        public static string ___Move_to_work_position_actuator__ {
            get {
                return ResourceManager.GetString("___Move_to_work_position_actuator__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to work position signal.
        /// </summary>
        public static string ___Move_to_work_position_signal__ {
            get {
                return ResourceManager.GetString("___Move_to_work_position_signal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement aborted due to.
        /// </summary>
        public static string ___Movement_aborted_due_to__ {
            get {
                return ResourceManager.GetString("___Movement_aborted_due_to__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        public static string ___STOP__ {
            get {
                return ResourceManager.GetString("___STOP__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string ___Work__ {
            get {
                return ResourceManager.GetString("___Work__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work position sensor.
        /// </summary>
        public static string ___Work_position_sensor__ {
            get {
                return ResourceManager.GetString("___Work_position_sensor__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work sensor signal.
        /// </summary>
        public static string ___Work_sensor_signal__ {
            get {
                return ResourceManager.GetString("___Work_sensor_signal__", resourceCulture);
            }
        }
    }
}
