<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3453" Id="{fc8fc785-be11-0ad3-27d3-b3ab02168737}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3453
VAR
	_io : EL3453_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{2dd1f1ca-e776-0c8a-1288-0670e78c07ba}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3453_Data]]></Declaration>
      <Get Name="Get" Id="{683d7bbe-f26a-02dd-38e8-c0c9895e54d7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{2927ce4b-5a88-061b-1c61-168a14cc281b}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{97b88493-2998-024b-2b33-7b5036589eea}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>