<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL5122" Id="{14cfafe3-91b0-0d6a-0ec5-621a855ae5fb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL5122
VAR
	_io : EL5122_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAdsDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{6432d7fb-7653-0cdb-041f-810b7e1d7652}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL5122_Data]]></Declaration>
      <Get Name="Get" Id="{c6f12ab3-6181-0d9a-17a0-6c7f106cfa6d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{62db1900-afe2-0547-214a-f9538e2d305e}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{8eef0600-efd9-062e-2e22-aa57533eac4b}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>