<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{9359a558-9122-0f04-2d2f-c4fb3f11651d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    myVeryFirstTcoContextInstance : TcoContext;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[myVeryFirstTcoContextInstance.Run();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>