{
 "title": "TcOpen",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Dynamic Image ",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "target": "LastMode", "type": "timeserie" }
   ]
  },
  {
   "title": "OK/NOK by Recipe",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 12, "x": 5, "y": 0 },
   "targets": [
    { "target": "OkNokByRecipe", "type": "timeserie" }
   ]
  },
  {
   "title": "Good count",
   "type": "stat",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "TotalOK", "type": "timeserie" }
   ]
  },
  {
   "title": "Recipe",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "LastMode", "type": "timeserie" }
   ]
  },
  {
   "title": "Station modes ",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "target": "StationModesTimeline", "type": "timeserie" }
   ]
  }
 ]
}