//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcOpen.Inxton.TcoUrRobotics.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcOpen.Inxton.TcoUrRobotics.Wpf.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is emergency stopped.
        /// </summary>
        public static string EmergencyStopped {
            get {
                return ResourceManager.GetString("EmergencyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is fault.
        /// </summary>
        public static string IsFault {
            get {
                return ResourceManager.GetString("IsFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is stopped due safety.
        /// </summary>
        public static string IsStoppedDueSafety {
            get {
                return ResourceManager.GetString("IsStoppedDueSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is violation.
        /// </summary>
        public static string IsViolation {
            get {
                return ResourceManager.GetString("IsViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key not in Auto.
        /// </summary>
        public static string KeyNotInAuto {
            get {
                return ResourceManager.GetString("KeyNotInAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motors On.
        /// </summary>
        public static string Motors_On {
            get {
                return ResourceManager.GetString("Motors On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motors Off.
        /// </summary>
        public static string MotorsOff {
            get {
                return ResourceManager.GetString("MotorsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is normal mode.
        /// </summary>
        public static string NormalMode {
            get {
                return ResourceManager.GetString("NormalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is stoped.
        /// </summary>
        public static string ProgramIsNotRunning {
            get {
                return ResourceManager.GetString("ProgramIsNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is running.
        /// </summary>
        public static string ProgramIsRunning {
            get {
                return ResourceManager.GetString("ProgramIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is protective stopped.
        /// </summary>
        public static string ProtectiveStopped {
            get {
                return ResourceManager.GetString("ProtectiveStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is recovery mode.
        /// </summary>
        public static string RecoveryMode {
            get {
                return ResourceManager.GetString("RecoveryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is reduced mode.
        /// </summary>
        public static string ReducedMode {
            get {
                return ResourceManager.GetString("ReducedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is robot emergency stopped.
        /// </summary>
        public static string RobotEmergencyStopped {
            get {
                return ResourceManager.GetString("RobotEmergencyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is safeguard stopped.
        /// </summary>
        public static string SafeguardStoppred {
            get {
                return ResourceManager.GetString("SafeguardStoppred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Error!.
        /// </summary>
        public static string SafetyError {
            get {
                return ResourceManager.GetString("SafetyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Ok.
        /// </summary>
        public static string SafetyOk {
            get {
                return ResourceManager.GetString("SafetyOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is system emergency stopped.
        /// </summary>
        public static string SystemEmergencyStopped {
            get {
                return ResourceManager.GetString("SystemEmergencyStopped", resourceCulture);
            }
        }
    }
}
