<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{773bf874-b264-48a0-a352-092af4113065}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	_digitalInspectorTests : DigitalInspectorTests;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_digitalInspectorTests.ProbeRun();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>