//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoKukaRoboticsConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoKukaRoboticsConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is OFF .
        /// </summary>
        public static string ____is_OFF___ {
            get {
                return ResourceManager.GetString("____is_OFF___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Waiting for signal: .
        /// </summary>
        public static string ____Waiting_for_signal____ {
            get {
                return ResourceManager.GetString("____Waiting_for_signal____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action number.
        /// </summary>
        public static string ___Action_number__ {
            get {
                return ResourceManager.GetString("___Action_number__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Interface [I_O_ACT].
        /// </summary>
        public static string ___Activate_Interface__I_O_ACT___ {
            get {
                return ResourceManager.GetString("___Activate_Interface__I_O_ACT___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlarmStopActive [ALARM_STOP].
        /// </summary>
        public static string ___AlarmStopActive__ALARM_STOP___ {
            get {
                return ResourceManager.GetString("___AlarmStopActive__ALARM_STOP___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic [AUT].
        /// </summary>
        public static string ___Automatic__AUT___ {
            get {
                return ResourceManager.GetString("___Automatic__AUT___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string ___Config__ {
            get {
                return ResourceManager.GetString("___Config__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string ___Control__ {
            get {
                return ResourceManager.GetString("___Control__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlReady [RC_RDY1].
        /// </summary>
        public static string ___ControlReady__RC_RDY1___ {
            get {
                return ResourceManager.GetString("___ControlReady__RC_RDY1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string ___Coordinates__ {
            get {
                return ResourceManager.GetString("___Coordinates__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives Off [DRIVES_OFF].
        /// </summary>
        public static string ___Drives_Off__DRIVES_OFF___ {
            get {
                return ResourceManager.GetString("___Drives_Off__DRIVES_OFF___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives On [DRIVES_ON].
        /// </summary>
        public static string ___Drives_On__DRIVES_ON___ {
            get {
                return ResourceManager.GetString("___Drives_On__DRIVES_ON___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrivesReady [PERI_RDY].
        /// </summary>
        public static string ___DrivesReady__PERI_RDY___ {
            get {
                return ResourceManager.GetString("___DrivesReady__PERI_RDY___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop active.
        /// </summary>
        public static string ___Emergency_stop_active__ {
            get {
                return ResourceManager.GetString("___Emergency_stop_active__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ___Error__ {
            get {
                return ResourceManager.GetString("___Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Confirmation [CONF_MESS].
        /// </summary>
        public static string ___Error_Confirmation__CONF_MESS___ {
            get {
                return ResourceManager.GetString("___Error_Confirmation__CONF_MESS___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCollection [STOPMESS].
        /// </summary>
        public static string ___ErrorCollection__STOPMESS___ {
            get {
                return ResourceManager.GetString("___ErrorCollection__STOPMESS___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event ID.
        /// </summary>
        public static string ___Event_ID__ {
            get {
                return ResourceManager.GetString("___Event_ID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalAutomatic [EXT].
        /// </summary>
        public static string ___ExternalAutomatic__EXT___ {
            get {
                return ResourceManager.GetString("___ExternalAutomatic__EXT___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global robot speed.
        /// </summary>
        public static string ___Global_robot_speed__ {
            get {
                return ResourceManager.GetString("___Global_robot_speed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global speed.
        /// </summary>
        public static string ___Global_speed__ {
            get {
                return ResourceManager.GetString("___Global_speed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        public static string ___IN__ {
            get {
                return ResourceManager.GetString("___IN__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 1.
        /// </summary>
        public static string ___In_area_1__ {
            get {
                return ResourceManager.GetString("___In_area_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 2.
        /// </summary>
        public static string ___In_area_2__ {
            get {
                return ResourceManager.GetString("___In_area_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 3.
        /// </summary>
        public static string ___In_area_3__ {
            get {
                return ResourceManager.GetString("___In_area_3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 4.
        /// </summary>
        public static string ___In_area_4__ {
            get {
                return ResourceManager.GetString("___In_area_4__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position.
        /// </summary>
        public static string ___In_position__ {
            get {
                return ResourceManager.GetString("___In_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 1.
        /// </summary>
        public static string ___In_position_1__ {
            get {
                return ResourceManager.GetString("___In_position_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 2.
        /// </summary>
        public static string ___In_position_2__ {
            get {
                return ResourceManager.GetString("___In_position_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 3.
        /// </summary>
        public static string ___In_position_3__ {
            get {
                return ResourceManager.GetString("___In_position_3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 4.
        /// </summary>
        public static string ___In_position_4__ {
            get {
                return ResourceManager.GetString("___In_position_4__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InHome [IN_HOME].
        /// </summary>
        public static string ___InHome__IN_HOME___ {
            get {
                return ResourceManager.GetString("___InHome__IN_HOME___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterfaceActivated [I_O_ACTCONF].
        /// </summary>
        public static string ___InterfaceActivated__I_O_ACTCONF___ {
            get {
                return ResourceManager.GetString("___InterfaceActivated__I_O_ACTCONF___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reference: .
        /// </summary>
        public static string ___Invalid_reference____ {
            get {
                return ResourceManager.GetString("___Invalid_reference____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reference StartMotorAndProgramTask.
        /// </summary>
        public static string ___Invalid_reference_StartMotorAndProgramTask__ {
            get {
                return ResourceManager.GetString("___Invalid_reference_StartMotorAndProgramTask__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual [T1].
        /// </summary>
        public static string ___Manual__T1___ {
            get {
                return ResourceManager.GetString("___Manual__T1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master mode.
        /// </summary>
        public static string ___Master_mode__ {
            get {
                return ResourceManager.GetString("___Master_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Enable [MOVE_ENABLE].
        /// </summary>
        public static string ___Move_Enable__MOVE_ENABLE___ {
            get {
                return ResourceManager.GetString("___Move_Enable__MOVE_ENABLE___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to position ID.
        /// </summary>
        public static string ___Moving_to_position_ID__ {
            get {
                return ResourceManager.GetString("___Moving_to_position_ID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT.
        /// </summary>
        public static string ___OUT__ {
            get {
                return ResourceManager.GetString("___OUT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PN Error.
        /// </summary>
        public static string ___PN_Error__ {
            get {
                return ResourceManager.GetString("___PN_Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point number.
        /// </summary>
        public static string ___Point_number__ {
            get {
                return ResourceManager.GetString("___Point_number__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PointNumber.
        /// </summary>
        public static string ___PointNumber__ {
            get {
                return ResourceManager.GetString("___PointNumber__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PpMoved.
        /// </summary>
        public static string ___PpMoved__ {
            get {
                return ResourceManager.GetString("___PpMoved__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcesActive [PRO_ACT].
        /// </summary>
        public static string ___ProcesActive__PRO_ACT___ {
            get {
                return ResourceManager.GetString("___ProcesActive__PRO_ACT___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Start [EXT_START].
        /// </summary>
        public static string ___Program_Start__EXT_START___ {
            get {
                return ResourceManager.GetString("___Program_Start__EXT_START___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgramMoveActive [PROGRAM MOVEMENT ACTIVE].
        /// </summary>
        public static string ___ProgramMoveActive__PROGRAM_MOVEMENT_ACTIVE___ {
            get {
                return ResourceManager.GetString("___ProgramMoveActive__PROGRAM_MOVEMENT_ACTIVE___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string ___Restore__ {
            get {
                return ResourceManager.GetString("___Restore__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Error Reset and Move Enable.
        /// </summary>
        public static string ___Robot_Error_Reset_and_Move_Enable__ {
            get {
                return ResourceManager.GetString("___Robot_Error_Reset_and_Move_Enable__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot reported an error: .
        /// </summary>
        public static string ___Robot_reported_an_error____ {
            get {
                return ResourceManager.GetString("___Robot_reported_an_error____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RobotCalibrated [ROB_CAL].
        /// </summary>
        public static string ___RobotCalibrated__ROB_CAL___ {
            get {
                return ResourceManager.GetString("___RobotCalibrated__ROB_CAL___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RobotStopped [ROB_STOPPED].
        /// </summary>
        public static string ___RobotStopped__ROB_STOPPED___ {
            get {
                return ResourceManager.GetString("___RobotStopped__ROB_STOPPED___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Error .
        /// </summary>
        public static string ___Safety_Error___ {
            get {
                return ResourceManager.GetString("___Safety_Error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at Main.
        /// </summary>
        public static string ___Start_at_Main__ {
            get {
                return ResourceManager.GetString("___Start_at_Main__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start At Main [START_AT_MAIN].
        /// </summary>
        public static string ___Start_At_Main__START_AT_MAIN___ {
            get {
                return ResourceManager.GetString("___Start_At_Main__START_AT_MAIN___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at Main finished with error..
        /// </summary>
        public static string ___Start_at_Main_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Start_at_Main_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at Main started..
        /// </summary>
        public static string ___Start_at_Main_started___ {
            get {
                return ResourceManager.GetString("___Start_at_Main_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at Main was aborted, while not yet completed!.
        /// </summary>
        public static string ___Start_at_Main_was_aborted__while_not_yet_completed___ {
            get {
                return ResourceManager.GetString("___Start_at_Main_was_aborted__while_not_yet_completed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at Main was completed successfully..
        /// </summary>
        public static string ___Start_at_Main_was_completed_successfully___ {
            get {
                return ResourceManager.GetString("___Start_at_Main_was_completed_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors.
        /// </summary>
        public static string ___Start_motors__ {
            get {
                return ResourceManager.GetString("___Start_motors__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors  finished successfully..
        /// </summary>
        public static string ___Start_motors__finished_successfully___ {
            get {
                return ResourceManager.GetString("___Start_motors__finished_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors, program and movements finished successfully..
        /// </summary>
        public static string ___Start_motors__program_and_movements_finished_successfully___ {
            get {
                return ResourceManager.GetString("___Start_motors__program_and_movements_finished_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors, program and movements finished with error..
        /// </summary>
        public static string ___Start_motors__program_and_movements_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Start_motors__program_and_movements_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors, program and movements stared..
        /// </summary>
        public static string ___Start_motors__program_and_movements_stared___ {
            get {
                return ResourceManager.GetString("___Start_motors__program_and_movements_stared___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors, program and movements was aborted, while not yet completed!.
        /// </summary>
        public static string ___Start_motors__program_and_movements_was_aborted__while_not_yet_completed___ {
            get {
                return ResourceManager.GetString("___Start_motors__program_and_movements_was_aborted__while_not_yet_completed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors  was aborted..
        /// </summary>
        public static string ___Start_motors__was_aborted___ {
            get {
                return ResourceManager.GetString("___Start_motors__was_aborted___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors and program.
        /// </summary>
        public static string ___Start_motors_and_program__ {
            get {
                return ResourceManager.GetString("___Start_motors_and_program__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors and program finished successfully..
        /// </summary>
        public static string ___Start_motors_and_program_finished_successfully___ {
            get {
                return ResourceManager.GetString("___Start_motors_and_program_finished_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors and program finished with error..
        /// </summary>
        public static string ___Start_motors_and_program_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Start_motors_and_program_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors and program started..
        /// </summary>
        public static string ___Start_motors_and_program_started___ {
            get {
                return ResourceManager.GetString("___Start_motors_and_program_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors and program was aborted..
        /// </summary>
        public static string ___Start_motors_and_program_was_aborted___ {
            get {
                return ResourceManager.GetString("___Start_motors_and_program_was_aborted___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors finished with error..
        /// </summary>
        public static string ___Start_motors_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Start_motors_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors program and movements.
        /// </summary>
        public static string ___Start_motors_program_and_movements__ {
            get {
                return ResourceManager.GetString("___Start_motors_program_and_movements__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start motors started..
        /// </summary>
        public static string ___Start_motors_started___ {
            get {
                return ResourceManager.GetString("___Start_motors_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start movements.
        /// </summary>
        public static string ___Start_movements__ {
            get {
                return ResourceManager.GetString("___Start_movements__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start movements finished successfully..
        /// </summary>
        public static string ___Start_movements_finished_successfully___ {
            get {
                return ResourceManager.GetString("___Start_movements_finished_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start movements finished with error..
        /// </summary>
        public static string ___Start_movements_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Start_movements_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start movements stared..
        /// </summary>
        public static string ___Start_movements_stared___ {
            get {
                return ResourceManager.GetString("___Start_movements_stared___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start movements was aborted, while not yet completed!.
        /// </summary>
        public static string ___Start_movements_was_aborted__while_not_yet_completed___ {
            get {
                return ResourceManager.GetString("___Start_movements_was_aborted__while_not_yet_completed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start program.
        /// </summary>
        public static string ___Start_program__ {
            get {
                return ResourceManager.GetString("___Start_program__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartAtMain.
        /// </summary>
        public static string ___StartAtMain__ {
            get {
                return ResourceManager.GetString("___StartAtMain__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ___Status__ {
            get {
                return ResourceManager.GetString("___Status__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop motors.
        /// </summary>
        public static string ___Stop_motors__ {
            get {
                return ResourceManager.GetString("___Stop_motors__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop motors finished with error..
        /// </summary>
        public static string ___Stop_motors_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Stop_motors_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop motors started..
        /// </summary>
        public static string ___Stop_motors_started___ {
            get {
                return ResourceManager.GetString("___Stop_motors_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop motors was completed successfully..
        /// </summary>
        public static string ___Stop_motors_was_completed_successfully___ {
            get {
                return ResourceManager.GetString("___Stop_motors_was_completed_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop movements.
        /// </summary>
        public static string ___Stop_movements__ {
            get {
                return ResourceManager.GetString("___Stop_movements__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop movements and program  was completed successfully..
        /// </summary>
        public static string ___Stop_movements_and_program__was_completed_successfully___ {
            get {
                return ResourceManager.GetString("___Stop_movements_and_program__was_completed_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop movements and program finished with error..
        /// </summary>
        public static string ___Stop_movements_and_program_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Stop_movements_and_program_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop movements and program started..
        /// </summary>
        public static string ___Stop_movements_and_program_started___ {
            get {
                return ResourceManager.GetString("___Stop_movements_and_program_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop movements and program was aborted, while not yet completed!.
        /// </summary>
        public static string ___Stop_movements_and_program_was_aborted__while_not_yet_completed___ {
            get {
                return ResourceManager.GetString("___Stop_movements_and_program_was_aborted__while_not_yet_completed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop movenents and program.
        /// </summary>
        public static string ___Stop_movenents_and_program__ {
            get {
                return ResourceManager.GetString("___Stop_movenents_and_program__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop program.
        /// </summary>
        public static string ___Stop_program__ {
            get {
                return ResourceManager.GetString("___Stop_program__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop program was aborted, while not yet completed!.
        /// </summary>
        public static string ___Stop_program_was_aborted__while_not_yet_completed___ {
            get {
                return ResourceManager.GetString("___Stop_program_was_aborted__while_not_yet_completed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop program was completed successfully..
        /// </summary>
        public static string ___Stop_program_was_completed_successfully___ {
            get {
                return ResourceManager.GetString("___Stop_program_was_completed_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping movement finished with error..
        /// </summary>
        public static string ___Stopping_movement_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Stopping_movement_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping movements started..
        /// </summary>
        public static string ___Stopping_movements_started___ {
            get {
                return ResourceManager.GetString("___Stopping_movements_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping movements was aborted, while not yet completed!.
        /// </summary>
        public static string ___Stopping_movements_was_aborted__while_not_yet_completed___ {
            get {
                return ResourceManager.GetString("___Stopping_movements_was_aborted__while_not_yet_completed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping movements was completed successfully..
        /// </summary>
        public static string ___Stopping_movements_was_completed_successfully___ {
            get {
                return ResourceManager.GetString("___Stopping_movements_was_completed_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping program started..
        /// </summary>
        public static string ___Stopping_program_started___ {
            get {
                return ResourceManager.GetString("___Stopping_program_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping program with error..
        /// </summary>
        public static string ___Stopping_program_with_error___ {
            get {
                return ResourceManager.GetString("___Stopping_program_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 1 extend.
        /// </summary>
        public static string ___Tool_1_extend__ {
            get {
                return ResourceManager.GetString("___Tool_1_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 1 retract.
        /// </summary>
        public static string ___Tool_1_retract__ {
            get {
                return ResourceManager.GetString("___Tool_1_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 2 extend.
        /// </summary>
        public static string ___Tool_2_extend__ {
            get {
                return ResourceManager.GetString("___Tool_2_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 2 retract.
        /// </summary>
        public static string ___Tool_2_retract__ {
            get {
                return ResourceManager.GetString("___Tool_2_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 3 extend.
        /// </summary>
        public static string ___Tool_3_extend__ {
            get {
                return ResourceManager.GetString("___Tool_3_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 3 retract.
        /// </summary>
        public static string ___Tool_3_retract__ {
            get {
                return ResourceManager.GetString("___Tool_3_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 4 extend.
        /// </summary>
        public static string ___Tool_4_extend__ {
            get {
                return ResourceManager.GetString("___Tool_4_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 4 retract.
        /// </summary>
        public static string ___Tool_4_retract__ {
            get {
                return ResourceManager.GetString("___Tool_4_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool number.
        /// </summary>
        public static string ___Tool_number__ {
            get {
                return ResourceManager.GetString("___Tool_number__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User specific speed 1.
        /// </summary>
        public static string ___User_specific_speed_1__ {
            get {
                return ResourceManager.GetString("___User_specific_speed_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User specific speed 2.
        /// </summary>
        public static string ___User_specific_speed_2__ {
            get {
                return ResourceManager.GetString("___User_specific_speed_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSafetySwitchClosed [USER_SAF].
        /// </summary>
        public static string ___UserSafetySwitchClosed__USER_SAF___ {
            get {
                return ResourceManager.GetString("___UserSafetySwitchClosed__USER_SAF___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for motors are On! .
        /// </summary>
        public static string ___Waiting_for_motors_are_On____ {
            get {
                return ResourceManager.GetString("___Waiting_for_motors_are_On____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for program running signal! .
        /// </summary>
        public static string ___Waiting_for_program_running_signal____ {
            get {
                return ResourceManager.GetString("___Waiting_for_program_running_signal____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for signal.
        /// </summary>
        public static string ___Waiting_for_signal__ {
            get {
                return ResourceManager.GetString("___Waiting_for_signal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for system is without errors! .
        /// </summary>
        public static string ___Waiting_for_system_is_without_errors____ {
            get {
                return ResourceManager.GetString("___Waiting_for_system_is_without_errors____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting program pointer changed! .
        /// </summary>
        public static string ___Waiting_program_pointer_changed____ {
            get {
                return ResourceManager.GetString("___Waiting_program_pointer_changed____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workobject number.
        /// </summary>
        public static string ___Workobject_number__ {
            get {
                return ResourceManager.GetString("___Workobject_number__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string ___Zones__ {
            get {
                return ResourceManager.GetString("___Zones__", resourceCulture);
            }
        }
    }
}
