<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2008" Id="{5b0fb1dc-9a25-0bf8-2ea3-7bcb79bcc0db}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2008
VAR
    {attribute addProperty Name "CHANNEL_"}
    _io : EL2008_Data;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{2116bbb0-141f-0dc9-1416-ab3df237f583}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2008_Data]]></Declaration>
      <Get Name="Get" Id="{395fd904-08c3-0851-06a4-9b0e8d860671}">
        <Declaration><![CDATA[VAR
END_VAR]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>