<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MainContext" Id="{7a93b1be-ffc4-072f-3445-b7477cb19895}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK INTERNAL MainContext EXTENDS TcoCore.TcoContext
VAR
	fbProcessDataManger : TcoDataExchange(THIS^);
	test : Entity;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Main" Id="{5b861888-c4dd-0ced-02c0-7cfc87b2ce81}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Main method of the TcoContext. This is the entry point of any control logic that belongs to this context. 
			The call of this method is ensured by calling the <c>InstanceName.Run()</c> method, and it must not be called explicitly.
			This method is abstract, and it must be overridden in derived block.
		</summary>
	</docu>
~*)
METHOD PROTECTED  Main]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>