<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1254" Id="{1d9895db-1860-0aa7-1372-d4aec8e6271f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1254
VAR
	_io : EL1254_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{008fc582-7408-0a24-2071-5f2dd2c9e5a7}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1254_Data]]></Declaration>
      <Get Name="Get" Id="{63f2143e-21b5-0bb3-3034-ccaa13445a3b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{49000252-c761-074a-24ca-4d4f35a12728}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{91c2dc24-524b-0f3e-1975-9ee5b28dd138}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>