<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LoggerContext" Id="{c46f76b3-06bd-0840-1299-159c746bcd7b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LoggerContext EXTENDS TcoCore.TcoContext
VAR
	_loggerUsage : LoggerUsage(THIS^);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Main" Id="{715a53a7-11bb-0341-1584-cfe2c07fcfc5}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Main method of the TcoContext. This is the entry point of any control logic that belongs to this context. 
			The call of this method is ensured by calling the <c>InstanceName.Run()</c> method, and it must not be called explicitly.
			This method is abstract, and it must be overridden in derived block.
		</summary>
	</docu>
~*)
METHOD PROTECTED  Main]]></Declaration>
      <Implementation>
        <ST><![CDATA[_loggerUsage();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>