<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{0f34ba18-e40b-0caf-2a51-227dede86d56}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    dataTests : TestDataContext;
    sandbox : SandboxContext;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[dataTests.ProbeRun();
sandbox.Run();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>