<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL6002" Id="{d1db44ba-78d9-0fd9-33b2-5acab59b90b0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL6002
VAR
	_io : EL6002_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{0da5ac30-c5da-06a8-0861-de3882a072f4}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL6002_Data]]></Declaration>
      <Get Name="Get" Id="{3fee0d14-1479-04f3-29aa-70d9bc37be58}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{d069826f-4ee8-0e0c-1ec7-7e2510946fc2}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{e4b5543d-1437-0d75-3749-abac6cda6cd5}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>