<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TcoDaq" Id="{8fe8c386-5d63-07cd-3c39-fabdbfd58ac3}" SpecialFunc="None">
    <Declaration><![CDATA[(*~
		<docu>
			<summary>
				Default implementation of DAQ.	
				<note type="tip">
					 This type is partially extended by IVF to retrieve data from the DAQ in IVF application.			
				</note>												 
			</summary>		
			<code>
			   // Intializes DAQ retrieval into applications logger
				..._daq.StartDaq();
			</code>
			<code>
				FUNCTION_BLOCK DaqUsage EXTENDS TcoCore.TcoObject
				VAR
					_daq : TcoCore.TcoDaq(THIS^);
					_counter : INT;
                    _myData : MyDataStruct;
				END_VAR
				//---------------------------------------------
				_counter := _counter + 1;
			    _daq.PushData(ADR(_myData), SIZEOF(MyDataStruct));
			</code>		
		</docu>
~*)
FUNCTION_BLOCK ABSTRACT TcoDaq EXTENDS TcoObject 
VAR	
	(*~
		<docu>
			<summary>
				Circular carret of of the DAQ buffer. 					 
			</summary>				
		</docu>
    ~*)
	_plcCarret : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Push" Id="{e510aa33-5ec3-0c2a-3bf2-b12b6de4083a}">
      <Declaration><![CDATA[METHOD ABSTRACT Push : BOOL
VAR_INPUT
	pData : PVOID;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>