<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3483" Id="{bd8d4db1-6c35-05ec-3694-e2664d2b4036}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3483
VAR
	_io : EL3483_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{f130d515-1aca-0189-0a29-7348d77f85ad}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3483_Data]]></Declaration>
      <Get Name="Get" Id="{7494767e-5b45-011b-15ef-8c76421cd251}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{d448308a-654a-0c5e-1c54-ed10bb5be6be}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{aebc04c5-f074-0ea9-1eed-386bd9d43c50}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>