//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoTixonFeedingConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoTixonFeedingConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink period.
        /// </summary>
        public static string ___Blink_period__ {
            get {
                return ResourceManager.GetString("___Blink_period__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blow A.
        /// </summary>
        public static string ___Blow_A__ {
            get {
                return ResourceManager.GetString("___Blow_A__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blow B.
        /// </summary>
        public static string ___Blow_B__ {
            get {
                return ResourceManager.GetString("___Blow_B__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer blow  active .
        /// </summary>
        public static string ___Buffer_blow__active___ {
            get {
                return ResourceManager.GetString("___Buffer_blow__active___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer blow on start.
        /// </summary>
        public static string ___Buffer_blow_on_start__ {
            get {
                return ResourceManager.GetString("___Buffer_blow_on_start__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer empty time to report.
        /// </summary>
        public static string ___Buffer_empty_time_to_report__ {
            get {
                return ResourceManager.GetString("___Buffer_empty_time_to_report__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer full blow time after.
        /// </summary>
        public static string ___Buffer_full_blow_time_after__ {
            get {
                return ResourceManager.GetString("___Buffer_full_blow_time_after__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer full time to report.
        /// </summary>
        public static string ___Buffer_full_time_to_report__ {
            get {
                return ResourceManager.GetString("___Buffer_full_time_to_report__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer task.
        /// </summary>
        public static string ___Buffer_task__ {
            get {
                return ResourceManager.GetString("___Buffer_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer task  finished successfully..
        /// </summary>
        public static string ___Buffer_task__finished_successfully___ {
            get {
                return ResourceManager.GetString("___Buffer_task__finished_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer task  was aborted..
        /// </summary>
        public static string ___Buffer_task__was_aborted___ {
            get {
                return ResourceManager.GetString("___Buffer_task__was_aborted___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer task finished with error..
        /// </summary>
        public static string ___Buffer_task_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Buffer_task_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer task started..
        /// </summary>
        public static string ___Buffer_task_started___ {
            get {
                return ResourceManager.GetString("___Buffer_task_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer time to idle.
        /// </summary>
        public static string ___Buffer_time_to_idle__ {
            get {
                return ResourceManager.GetString("___Buffer_time_to_idle__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component is ready.
        /// </summary>
        public static string ___Component_is_ready__ {
            get {
                return ResourceManager.GetString("___Component_is_ready__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component out of box.
        /// </summary>
        public static string ___Component_out_of_box__ {
            get {
                return ResourceManager.GetString("___Component_out_of_box__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string ___Config__ {
            get {
                return ResourceManager.GetString("___Config__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string ___Control__ {
            get {
                return ResourceManager.GetString("___Control__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error time buffer .
        /// </summary>
        public static string ___Error_time_buffer___ {
            get {
                return ResourceManager.GetString("___Error_time_buffer___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error time Hopper .
        /// </summary>
        public static string ___Error_time_Hopper___ {
            get {
                return ResourceManager.GetString("___Error_time_Hopper___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error time separator .
        /// </summary>
        public static string ___Error_time_separator___ {
            get {
                return ResourceManager.GetString("___Error_time_separator___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error time Stepper .
        /// </summary>
        public static string ___Error_time_Stepper___ {
            get {
                return ResourceManager.GetString("___Error_time_Stepper___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeder blow B  active .
        /// </summary>
        public static string ___Feeder_blow_B__active___ {
            get {
                return ResourceManager.GetString("___Feeder_blow_B__active___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeder blow B on start.
        /// </summary>
        public static string ___Feeder_blow_B_on_start__ {
            get {
                return ResourceManager.GetString("___Feeder_blow_B_on_start__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeder empty time to report.
        /// </summary>
        public static string ___Feeder_empty_time_to_report__ {
            get {
                return ResourceManager.GetString("___Feeder_empty_time_to_report__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeder full blow B time after.
        /// </summary>
        public static string ___Feeder_full_blow_B_time_after__ {
            get {
                return ResourceManager.GetString("___Feeder_full_blow_B_time_after__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeder has components.
        /// </summary>
        public static string ___Feeder_has_components__ {
            get {
                return ResourceManager.GetString("___Feeder_has_components__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeding A .
        /// </summary>
        public static string ___Feeding_A___ {
            get {
                return ResourceManager.GetString("___Feeding_A___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeding B.
        /// </summary>
        public static string ___Feeding_B__ {
            get {
                return ResourceManager.GetString("___Feeding_B__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing sensor.
        /// </summary>
        public static string ___Filing_sensor__ {
            get {
                return ResourceManager.GetString("___Filing_sensor__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green led.
        /// </summary>
        public static string ___Green_led__ {
            get {
                return ResourceManager.GetString("___Green_led__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooper.
        /// </summary>
        public static string ___Hooper__ {
            get {
                return ResourceManager.GetString("___Hooper__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooper is active.
        /// </summary>
        public static string ___Hooper_is_active__ {
            get {
                return ResourceManager.GetString("___Hooper_is_active__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopper is running.
        /// </summary>
        public static string ___Hopper_is_running__ {
            get {
                return ResourceManager.GetString("___Hopper_is_running__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopper task.
        /// </summary>
        public static string ___Hopper_task__ {
            get {
                return ResourceManager.GetString("___Hopper_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopper task  finished successfully..
        /// </summary>
        public static string ___Hopper_task__finished_successfully___ {
            get {
                return ResourceManager.GetString("___Hopper_task__finished_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopper task  was aborted..
        /// </summary>
        public static string ___Hopper_task__was_aborted___ {
            get {
                return ResourceManager.GetString("___Hopper_task__was_aborted___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopper task finished with error..
        /// </summary>
        public static string ___Hopper_task_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Hopper_task_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopper task started..
        /// </summary>
        public static string ___Hopper_task_started___ {
            get {
                return ResourceManager.GetString("___Hopper_task_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Pick Zone.
        /// </summary>
        public static string ___In_Pick_Zone__ {
            get {
                return ResourceManager.GetString("___In_Pick_Zone__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reference: .
        /// </summary>
        public static string ___Invalid_reference____ {
            get {
                return ResourceManager.GetString("___Invalid_reference____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red led.
        /// </summary>
        public static string ___Red_led__ {
            get {
                return ResourceManager.GetString("___Red_led__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string ___Restore__ {
            get {
                return ResourceManager.GetString("___Restore__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator  active .
        /// </summary>
        public static string ___Separator__active___ {
            get {
                return ResourceManager.GetString("___Separator__active___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator in home position.
        /// </summary>
        public static string ___Separator_in_home_position__ {
            get {
                return ResourceManager.GetString("___Separator_in_home_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator in work position.
        /// </summary>
        public static string ___Separator_in_work_position__ {
            get {
                return ResourceManager.GetString("___Separator_in_work_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator present.
        /// </summary>
        public static string ___Separator_present__ {
            get {
                return ResourceManager.GetString("___Separator_present__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator task.
        /// </summary>
        public static string ___Separator_task__ {
            get {
                return ResourceManager.GetString("___Separator_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator task  finished successfully..
        /// </summary>
        public static string ___Separator_task__finished_successfully___ {
            get {
                return ResourceManager.GetString("___Separator_task__finished_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator task  was aborted..
        /// </summary>
        public static string ___Separator_task__was_aborted___ {
            get {
                return ResourceManager.GetString("___Separator_task__was_aborted___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator task finished with error..
        /// </summary>
        public static string ___Separator_task_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Separator_task_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator task started..
        /// </summary>
        public static string ___Separator_task_started___ {
            get {
                return ResourceManager.GetString("___Separator_task_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separe component.
        /// </summary>
        public static string ___Separe_component__ {
            get {
                return ResourceManager.GetString("___Separe_component__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot component.
        /// </summary>
        public static string ___Shot_component__ {
            get {
                return ResourceManager.GetString("___Shot_component__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start  vibratorating and blowing.
        /// </summary>
        public static string ___Start__vibratorating_and_blowing__ {
            get {
                return ResourceManager.GetString("___Start__vibratorating_and_blowing__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ___Status__ {
            get {
                return ResourceManager.GetString("___Status__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step task.
        /// </summary>
        public static string ___Step_task__ {
            get {
                return ResourceManager.GetString("___Step_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper in home position.
        /// </summary>
        public static string ___Stepper_in_home_position__ {
            get {
                return ResourceManager.GetString("___Stepper_in_home_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper in work position.
        /// </summary>
        public static string ___Stepper_in_work_position__ {
            get {
                return ResourceManager.GetString("___Stepper_in_work_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper task  finished successfully..
        /// </summary>
        public static string ___Stepper_task__finished_successfully___ {
            get {
                return ResourceManager.GetString("___Stepper_task__finished_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper task  was aborted..
        /// </summary>
        public static string ___Stepper_task__was_aborted___ {
            get {
                return ResourceManager.GetString("___Stepper_task__was_aborted___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper task finished with error..
        /// </summary>
        public static string ___Stepper_task_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Stepper_task_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper task started..
        /// </summary>
        public static string ___Stepper_task_started___ {
            get {
                return ResourceManager.GetString("___Stepper_task_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper to home.
        /// </summary>
        public static string ___Stepper_to_home__ {
            get {
                return ResourceManager.GetString("___Stepper_to_home__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper to work.
        /// </summary>
        public static string ___Stepper_to_work__ {
            get {
                return ResourceManager.GetString("___Stepper_to_work__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper valve.
        /// </summary>
        public static string ___Stepper_valve__ {
            get {
                return ResourceManager.GetString("___Stepper_valve__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to hopper run .
        /// </summary>
        public static string ___Time_to_hopper_run___ {
            get {
                return ResourceManager.GetString("___Time_to_hopper_run___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to hopper start .
        /// </summary>
        public static string ___Time_to_hopper_start___ {
            get {
                return ResourceManager.GetString("___Time_to_hopper_start___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time when component in separator .
        /// </summary>
        public static string ___Time_when_component_in_separator___ {
            get {
                return ResourceManager.GetString("___Time_when_component_in_separator___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time when component is out of separator .
        /// </summary>
        public static string ___Time_when_component_is_out_of_separator___ {
            get {
                return ResourceManager.GetString("___Time_when_component_is_out_of_separator___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time when stepper in home .
        /// </summary>
        public static string ___Time_when_stepper_in_home___ {
            get {
                return ResourceManager.GetString("___Time_when_stepper_in_home___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time when stepper in work .
        /// </summary>
        public static string ___Time_when_stepper_in_work___ {
            get {
                return ResourceManager.GetString("___Time_when_stepper_in_work___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tixon control system not in auto .
        /// </summary>
        public static string ___Tixon_control_system_not_in_auto___ {
            get {
                return ResourceManager.GetString("___Tixon_control_system_not_in_auto___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tixon controller in auto.
        /// </summary>
        public static string ___Tixon_controller_in_auto__ {
            get {
                return ResourceManager.GetString("___Tixon_controller_in_auto__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vib. bin task  finished successfully..
        /// </summary>
        public static string ___Vib__bin_task__finished_successfully___ {
            get {
                return ResourceManager.GetString("___Vib__bin_task__finished_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vib. bin task  was aborted..
        /// </summary>
        public static string ___Vib__bin_task__was_aborted___ {
            get {
                return ResourceManager.GetString("___Vib__bin_task__was_aborted___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vib. bin task finished with error..
        /// </summary>
        public static string ___Vib__bin_task_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Vib__bin_task_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vib. bin task started..
        /// </summary>
        public static string ___Vib__bin_task_started___ {
            get {
                return ResourceManager.GetString("___Vib__bin_task_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrating bin task.
        /// </summary>
        public static string ___Vibrating_bin_task__ {
            get {
                return ResourceManager.GetString("___Vibrating_bin_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for .
        /// </summary>
        public static string ___Waiting_for___ {
            get {
                return ResourceManager.GetString("___Waiting_for___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for blow B on .
        /// </summary>
        public static string ___Waiting_for_blow_B_on___ {
            get {
                return ResourceManager.GetString("___Waiting_for_blow_B_on___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for blow on .
        /// </summary>
        public static string ___Waiting_for_blow_on___ {
            get {
                return ResourceManager.GetString("___Waiting_for_blow_on___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for buffer empty.
        /// </summary>
        public static string ___Waiting_for_buffer_empty__ {
            get {
                return ResourceManager.GetString("___Waiting_for_buffer_empty__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for buffer full.
        /// </summary>
        public static string ___Waiting_for_buffer_full__ {
            get {
                return ResourceManager.GetString("___Waiting_for_buffer_full__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for buffer is Empty .
        /// </summary>
        public static string ___Waiting_for_buffer_is_Empty___ {
            get {
                return ResourceManager.GetString("___Waiting_for_buffer_is_Empty___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for buffer is full adn blow ending.
        /// </summary>
        public static string ___Waiting_for_buffer_is_full_adn_blow_ending__ {
            get {
                return ResourceManager.GetString("___Waiting_for_buffer_is_full_adn_blow_ending__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for buffer is full and blow ending.
        /// </summary>
        public static string ___Waiting_for_buffer_is_full_and_blow_ending__ {
            get {
                return ResourceManager.GetString("___Waiting_for_buffer_is_full_and_blow_ending__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for buffer is full and go idle.
        /// </summary>
        public static string ___Waiting_for_buffer_is_full_and_go_idle__ {
            get {
                return ResourceManager.GetString("___Waiting_for_buffer_is_full_and_go_idle__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for component in  separator.
        /// </summary>
        public static string ___Waiting_for_component_in__separator__ {
            get {
                return ResourceManager.GetString("___Waiting_for_component_in__separator__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for component in Pick position.
        /// </summary>
        public static string ___Waiting_for_component_in_Pick_position__ {
            get {
                return ResourceManager.GetString("___Waiting_for_component_in_Pick_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for component out of  separator.
        /// </summary>
        public static string ___Waiting_for_component_out_of__separator__ {
            get {
                return ResourceManager.GetString("___Waiting_for_component_out_of__separator__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for feeder empty.
        /// </summary>
        public static string ___Waiting_for_feeder_empty__ {
            get {
                return ResourceManager.GetString("___Waiting_for_feeder_empty__", resourceCulture);
            }
        }
    }
}
