<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2014" Id="{004e72ac-9486-0f99-2456-888dea05c566}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2014
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2014_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{36f115ba-c929-0934-203a-89a93c903863}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2014_Data]]></Declaration>
      <Get Name="Get" Id="{5f03d0e3-6396-00d8-384b-0dcbbdb07987}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{45e0171b-0e5f-0fc4-0c9f-2682f002d393}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{c86f7e9a-2e27-0f3a-075a-8eb5b4e3e1cf}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>