<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2044" Id="{294e1e75-1edd-0b24-34ca-30044f55b5db}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2044
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2044_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{041d236d-cc09-02f0-18d0-84f96a2561ac}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2044_Data]]></Declaration>
      <Get Name="Get" Id="{30daf7e6-d456-0bd1-35ef-6d13d00ada7e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{ee72c114-a2c3-04ee-3c44-19031c86d5d3}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{e26fc1ca-f550-06ec-1477-3cd6df0b8135}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>