<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2819" Id="{f59ad031-df69-0dad-3dc7-bd4977e4bd0a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2819
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
	_io : EL2819_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{1cfe1976-74d7-0229-2b9b-79837d9d1d6d}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2819_Data]]></Declaration>
      <Get Name="Get" Id="{b3e15092-72fc-05c9-1e8a-1747390738f5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{f8a26ab3-1d06-0816-34c0-3e40777fd7e2}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{25ab493c-172e-040d-1d16-e946f9a90b60}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>