//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoInspectorsConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoInspectorsConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrary error code for this inspection.
        /// </summary>
        internal static string ___Arbitrary_error_code_for_this_inspection__ {
            get {
                return ResourceManager.GetString("___Arbitrary_error_code_for_this_inspection__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts.
        /// </summary>
        internal static string ___Attempts__ {
            get {
                return ResourceManager.GetString("___Attempts__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief failure desciption.
        /// </summary>
        internal static string ___Brief_failure_desciption__ {
            get {
                return ResourceManager.GetString("___Brief_failure_desciption__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass.
        /// </summary>
        internal static string ___Bypass__ {
            get {
                return ResourceManager.GetString("___Bypass__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ___Code__ {
            get {
                return ResourceManager.GetString("___Code__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected.
        /// </summary>
        internal static string ___Detected__ {
            get {
                return ResourceManager.GetString("___Detected__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected data.
        /// </summary>
        internal static string ___Detected_data__ {
            get {
                return ResourceManager.GetString("___Detected_data__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected value.
        /// </summary>
        internal static string ___Detected_value__ {
            get {
                return ResourceManager.GetString("___Detected_value__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays detected status of this check..
        /// </summary>
        internal static string ___Displays_detected_status_of_this_check___ {
            get {
                return ResourceManager.GetString("___Displays_detected_status_of_this_check___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        internal static string ___Exclude__ {
            get {
                return ResourceManager.GetString("___Exclude__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure description.
        /// </summary>
        internal static string ___Failure_description__ {
            get {
                return ResourceManager.GetString("___Failure_description__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection is excluded from the evaluation. The test will however run and provide detected value..
        /// </summary>
        internal static string ___Inspection_is_excluded_from_the_evaluation__The_test_will_however_run_and_provide_detected_value___ {
            get {
                return ResourceManager.GetString("___Inspection_is_excluded_from_the_evaluation__The_test_will_however_run_and_prov" +
                        "ide_detected_value___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection will repeat given number of times when inspection fails..
        /// </summary>
        internal static string ___Inspection_will_repeat_given_number_of_times_when_inspection_fails___ {
            get {
                return ResourceManager.GetString("___Inspection_will_repeat_given_number_of_times_when_inspection_fails___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max..
        /// </summary>
        internal static string ___Max___ {
            get {
                return ResourceManager.GetString("___Max___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. value for the inspection to pass..
        /// </summary>
        internal static string ___Max__value_for_the_inspection_to_pass___ {
            get {
                return ResourceManager.GetString("___Max__value_for_the_inspection_to_pass___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min..
        /// </summary>
        internal static string ___Min___ {
            get {
                return ResourceManager.GetString("___Min___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. value for the inspection to pass..
        /// </summary>
        internal static string ___Min__value_for_the_inspection_to_pass___ {
            get {
                return ResourceManager.GetString("___Min__value_for_the_inspection_to_pass___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-tries.
        /// </summary>
        internal static string ___Re_tries__ {
            get {
                return ResourceManager.GetString("___Re_tries__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-tries counter, count the number of times the inspection run on this inspector instance..
        /// </summary>
        internal static string ___Re_tries_counter__count_the_number_of_times_the_inspection_run_on_this_inspector_instance___ {
            get {
                return ResourceManager.GetString("___Re_tries_counter__count_the_number_of_times_the_inspection_run_on_this_inspect" +
                        "or_instance___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string ___Required__ {
            get {
                return ResourceManager.GetString("___Required__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required status for inspection to pass. Can contain pattern string when `Star notation is enabled`.
        /// </summary>
        internal static string ___Required_status_for_inspection_to_pass__Can_contain_pattern_string_when__Star_notation_is_enabled___ {
            get {
                return ResourceManager.GetString("___Required_status_for_inspection_to_pass__Can_contain_pattern_string_when__Star_" +
                        "notation_is_enabled___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string ___Result__ {
            get {
                return ResourceManager.GetString("___Result__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of the inspection..
        /// </summary>
        internal static string ___Result_of_the_inspection___ {
            get {
                return ResourceManager.GetString("___Result_of_the_inspection___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the required status for the inspection to pass..
        /// </summary>
        internal static string ___Sets_the_required_status_for_the_inspection_to_pass___ {
            get {
                return ResourceManager.GetString("___Sets_the_required_status_for_the_inspection_to_pass___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stab.Time.
        /// </summary>
        internal static string ___Stab_Time__ {
            get {
                return ResourceManager.GetString("___Stab_Time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilisation time. The inspection will pass when the condition is met continuously for the duration of this timespan..
        /// </summary>
        internal static string ___Stabilisation_time__The_inspection_will_pass_when_the_condition_is_met_continuously_for_the_duration_of_this_timespan___ {
            get {
                return ResourceManager.GetString("___Stabilisation_time__The_inspection_will_pass_when_the_condition_is_met_continu" +
                        "ously_for_the_duration_of_this_timespan___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test is bypassed, no eveluation occurs..
        /// </summary>
        internal static string ___Test_is_bypassed__no_eveluation_occurs___ {
            get {
                return ResourceManager.GetString("___Test_is_bypassed__no_eveluation_occurs___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time stamp.
        /// </summary>
        internal static string ___Time_stamp__ {
            get {
                return ResourceManager.GetString("___Time_stamp__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string ___Timeout__ {
            get {
                return ResourceManager.GetString("___Timeout__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout. Maximal duration of the inspection within which the condition must be met..
        /// </summary>
        internal static string ___Timeout__Maximal_duration_of_the_inspection_within_which_the_condition_must_be_met___ {
            get {
                return ResourceManager.GetString("___Timeout__Maximal_duration_of_the_inspection_within_which_the_condition_must_be" +
                        "_met___", resourceCulture);
            }
        }
    }
}
