<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2595" Id="{17ecf101-0b3c-068d-385f-cc54f89d8bd7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2595
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
	_io : EL2595_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{2630bb96-651e-0abb-1f37-0f2222121b11}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2595_Data]]></Declaration>
      <Get Name="Get" Id="{c67e9241-54a9-0e23-030d-6fef5faac66e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{eb42528a-c217-08f5-0eb7-bfd23df9ce17}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{2683ea18-794e-0651-2058-1766e04d63aa}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>