<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2008" Id="{5950e863-1fda-088d-18bb-4d096c4607c1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2008
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2xx8_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{93a8bf92-fc89-0efb-0133-a62f67426657}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2xx8_Data]]></Declaration>
      <Get Name="Get" Id="{b666080f-8fd3-03f6-35d3-469a4e0c19e9}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{04e6eb73-ec5c-0c1e-03da-461c45997938}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{731629be-8866-0f19-2a0d-326c5e2aa9b6}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>