<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2828" Id="{9a40c7a0-20cc-0667-0514-799ad0ba3505}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2828
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2xx8_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{30c4182b-76ef-0d65-1b0f-32c45dc52875}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2xx8_Data]]></Declaration>
      <Get Name="Get" Id="{c03707dd-3020-05f9-07f4-3f06622122a5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{07f3c48c-51b4-0e83-3bee-91131e8155ef}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{067fdb50-c83b-08bf-3b08-724ca27b48ac}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>