//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoDrivesBeckhoffTestsConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoDrivesBeckhoffTestsConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlazkoPosition  Position.
        /// </summary>
        public static string ___BlazkoPosition__Position__ {
            get {
                return ResourceManager.GetString("___BlazkoPosition__Position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Position.
        /// </summary>
        public static string ___Pick_Position__ {
            get {
                return ResourceManager.GetString("___Pick_Position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place  Position.
        /// </summary>
        public static string ___Place__Position__ {
            get {
                return ResourceManager.GetString("___Place__Position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test axis 1.
        /// </summary>
        public static string ___Test_axis_1__ {
            get {
                return ResourceManager.GetString("___Test_axis_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test axis 2.
        /// </summary>
        public static string ___Test_axis_2__ {
            get {
                return ResourceManager.GetString("___Test_axis_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test multi axis.
        /// </summary>
        public static string ___Test_multi_axis__ {
            get {
                return ResourceManager.GetString("___Test_multi_axis__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test multi positions.
        /// </summary>
        public static string ___Test_multi_positions__ {
            get {
                return ResourceManager.GetString("___Test_multi_positions__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test positions.
        /// </summary>
        public static string ___Test_positions__ {
            get {
                return ResourceManager.GetString("___Test_positions__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test single axis.
        /// </summary>
        public static string ___Test_single_axis__ {
            get {
                return ResourceManager.GetString("___Test_single_axis__", resourceCulture);
            }
        }
    }
}
