//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoElementsConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoElementsConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calulate next expected Id position.
        /// </summary>
        internal static string ___Calulate_next_expected_Id_position__ {
            get {
                return ResourceManager.GetString("___Calulate_next_expected_Id_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Off.
        /// </summary>
        internal static string ___Check_Off__ {
            get {
                return ResourceManager.GetString("___Check_Off__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check On.
        /// </summary>
        internal static string ___Check_On__ {
            get {
                return ResourceManager.GetString("___Check_On__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks that the input is off.
        /// </summary>
        internal static string ___Checks_that_the_input_is_off__ {
            get {
                return ResourceManager.GetString("___Checks_that_the_input_is_off__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks that the input is on.
        /// </summary>
        internal static string ___Checks_that_the_input_is_on__ {
            get {
                return ResourceManager.GetString("___Checks_that_the_input_is_on__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string ___Config__ {
            get {
                return ResourceManager.GetString("___Config__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position.
        /// </summary>
        internal static string ___Current_position__ {
            get {
                return ResourceManager.GetString("___Current_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division by zero: Verify values defined in config! (RawHigh,RawLow).
        /// </summary>
        internal static string ___Division_by_zero__Verify_values_defined_in_config___RawHigh_RawLow___ {
            get {
                return ResourceManager.GetString("___Division_by_zero__Verify_values_defined_in_config___RawHigh_RawLow___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable turn.
        /// </summary>
        internal static string ___Enable_turn__ {
            get {
                return ResourceManager.GetString("___Enable_turn__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable turn signal.
        /// </summary>
        internal static string ___Enable_turn_signal__ {
            get {
                return ResourceManager.GetString("___Enable_turn_signal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable turn table.
        /// </summary>
        internal static string ___Enable_turn_table__ {
            get {
                return ResourceManager.GetString("___Enable_turn_table__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected next position.
        /// </summary>
        internal static string ___Expected_next_position__ {
            get {
                return ResourceManager.GetString("___Expected_next_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting table in position. .
        /// </summary>
        internal static string ___Expecting_table_in_position____ {
            get {
                return ResourceManager.GetString("___Expecting_table_in_position____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position.
        /// </summary>
        internal static string ___In_position__ {
            get {
                return ResourceManager.GetString("___In_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position sensor.
        /// </summary>
        internal static string ___In_position_sensor__ {
            get {
                return ResourceManager.GetString("___In_position_sensor__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position signal.
        /// </summary>
        internal static string ___In_position_signal__ {
            get {
                return ResourceManager.GetString("___In_position_signal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In precise position.
        /// </summary>
        internal static string ___In_precise_position__ {
            get {
                return ResourceManager.GetString("___In_precise_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In precise position sensor.
        /// </summary>
        internal static string ___In_precise_position_sensor__ {
            get {
                return ResourceManager.GetString("___In_precise_position_sensor__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In precise position signal.
        /// </summary>
        internal static string ___In_precise_position_signal__ {
            get {
                return ResourceManager.GetString("___In_precise_position_signal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrectly coded current position. Check configuration of code bits! .
        /// </summary>
        internal static string ___Incorrectly_coded_current_position__Check_configuration_of_code_bits____ {
            get {
                return ResourceManager.GetString("___Incorrectly_coded_current_position__Check_configuration_of_code_bits____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data: Gain is not defined!.
        /// </summary>
        internal static string ___Invalid_data__Gain_is_not_defined___ {
            get {
                return ResourceManager.GetString("___Invalid_data__Gain_is_not_defined___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reference: .
        /// </summary>
        internal static string ___Invalid_reference____ {
            get {
                return ResourceManager.GetString("___Invalid_reference____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string ___Off__ {
            get {
                return ResourceManager.GetString("___Off__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ___On__ {
            get {
                return ResourceManager.GetString("___On__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of boundaries,check correction parameters (Gain,Ofset) in config!.
        /// </summary>
        internal static string ___Out_of_boundaries_check_correction_parameters__Gain_Ofset__in_config___ {
            get {
                return ResourceManager.GetString("___Out_of_boundaries_check_correction_parameters__Gain_Ofset__in_config___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter number of positions is &lt;= 0. The paremeters must be grater than 0..
        /// </summary>
        internal static string ___Parameter_number_of_positions_is____0__The_paremeters_must_be_grater_than_0___ {
            get {
                return ResourceManager.GetString("___Parameter_number_of_positions_is____0__The_paremeters_must_be_grater_than_0___" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        internal static string ___Positions__ {
            get {
                return ResourceManager.GetString("___Positions__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw range.
        /// </summary>
        internal static string ___Raw_range__ {
            get {
                return ResourceManager.GetString("___Raw_range__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real range.
        /// </summary>
        internal static string ___Real_range__ {
            get {
                return ResourceManager.GetString("___Real_range__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required position must be in range 1 - 20 but was:.
        /// </summary>
        internal static string ___Required_position_must_be_in_range_1___20_but_was___ {
            get {
                return ResourceManager.GetString("___Required_position_must_be_in_range_1___20_but_was___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseting signal (off/false).
        /// </summary>
        internal static string ___Reseting_signal__off_false___ {
            get {
                return ResourceManager.GetString("___Reseting_signal__off_false___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the output.
        /// </summary>
        internal static string ___Resets_the_output__ {
            get {
                return ResourceManager.GetString("___Resets_the_output__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string ___Restore__ {
            get {
                return ResourceManager.GetString("___Restore__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety conditions to turn the table are not met..
        /// </summary>
        internal static string ___Safety_conditions_to_turn_the_table_are_not_met___ {
            get {
                return ResourceManager.GetString("___Safety_conditions_to_turn_the_table_are_not_met___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaled value.
        /// </summary>
        internal static string ___Scaled_value__ {
            get {
                return ResourceManager.GetString("___Scaled_value__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setpoint.
        /// </summary>
        internal static string ___Setpoint__ {
            get {
                return ResourceManager.GetString("___Setpoint__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the output.
        /// </summary>
        internal static string ___Sets_the_output__ {
            get {
                return ResourceManager.GetString("___Sets_the_output__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting signal (on/true).
        /// </summary>
        internal static string ___Setting_signal__on_true___ {
            get {
                return ResourceManager.GetString("___Setting_signal__on_true___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        internal static string ___Signal__ {
            get {
                return ResourceManager.GetString("___Signal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start turn.
        /// </summary>
        internal static string ___Start_turn__ {
            get {
                return ResourceManager.GetString("___Start_turn__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start turn signal.
        /// </summary>
        internal static string ___Start_turn_signal__ {
            get {
                return ResourceManager.GetString("___Start_turn_signal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start turn table.
        /// </summary>
        internal static string ___Start_turn_table__ {
            get {
                return ResourceManager.GetString("___Start_turn_table__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ___Status__ {
            get {
                return ResourceManager.GetString("___Status__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table after turn does not have expected coding. Expected id at position #1 is.
        /// </summary>
        internal static string ___Table_after_turn_does_not_have_expected_coding__Expected_id_at_position__1_is__ {
            get {
                return ResourceManager.GetString("___Table_after_turn_does_not_have_expected_coding__Expected_id_at_position__1_is_" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table turning. Trying to leave sensor.
        /// </summary>
        internal static string ___Table_turning__Trying_to_leave_sensor__ {
            get {
                return ResourceManager.GetString("___Table_turning__Trying_to_leave_sensor__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table turning. Trying to reach sensor table in positon..
        /// </summary>
        internal static string ___Table_turning__Trying_to_reach_sensor_table_in_positon___ {
            get {
                return ResourceManager.GetString("___Table_turning__Trying_to_reach_sensor_table_in_positon___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truning table  was completed successfully..
        /// </summary>
        internal static string ___Truning_table__was_completed_successfully___ {
            get {
                return ResourceManager.GetString("___Truning_table__was_completed_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        internal static string ___Turn__ {
            get {
                return ResourceManager.GetString("___Turn__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn safety condition.
        /// </summary>
        internal static string ___Turn_safety_condition__ {
            get {
                return ResourceManager.GetString("___Turn_safety_condition__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning table aborted due to.
        /// </summary>
        internal static string ___Turning_table_aborted_due_to__ {
            get {
                return ResourceManager.GetString("___Turning_table_aborted_due_to__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning table aborted due to NOT .
        /// </summary>
        internal static string ___Turning_table_aborted_due_to_NOT___ {
            get {
                return ResourceManager.GetString("___Turning_table_aborted_due_to_NOT___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning table finished with an error..
        /// </summary>
        internal static string ___Turning_table_finished_with_an_error___ {
            get {
                return ResourceManager.GetString("___Turning_table_finished_with_an_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning table is suspended due to.
        /// </summary>
        internal static string ___Turning_table_is_suspended_due_to__ {
            get {
                return ResourceManager.GetString("___Turning_table_is_suspended_due_to__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning table is suspended due to NOT .
        /// </summary>
        internal static string ___Turning_table_is_suspended_due_to_NOT___ {
            get {
                return ResourceManager.GetString("___Turning_table_is_suspended_due_to_NOT___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning table started..
        /// </summary>
        internal static string ___Turning_table_started___ {
            get {
                return ResourceManager.GetString("___Turning_table_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning table was aborted, while not yet completed!.
        /// </summary>
        internal static string ___Turning_table_was_aborted__while_not_yet_completed___ {
            get {
                return ResourceManager.GetString("___Turning_table_was_aborted__while_not_yet_completed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unscaled value.
        /// </summary>
        internal static string ___Unscaled_value__ {
            get {
                return ResourceManager.GetString("___Unscaled_value__", resourceCulture);
            }
        }
    }
}
