<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2252" Id="{b70986d3-5337-04f9-1022-1f990c4ef203}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2252
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataDC;
	_io : EL2252_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{aedd889d-3515-0a9e-09b0-1c889e479b85}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2252_Data]]></Declaration>
      <Get Name="Get" Id="{471d8ac7-09a5-0134-0f57-1ee419b9cdea}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{7b7b30f2-95bc-0da6-3b70-4b36c0022196}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{8eaf57ad-d1c0-0c92-227d-cb22cdfd7e60}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>