<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Horse_Object" Id="{318d333c-8793-0528-10f0-90d7a7341f0d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Horse_Object EXTENDS TcoObject
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>