<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Thomas_ObjectTaskExt" Id="{ae149a3c-b374-0b8a-1372-b7205850bf17}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Thomas_ObjectTaskExt EXTENDS Thomas_Object
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>