<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1008" Id="{33989b2f-810a-03a7-277e-b3e9dec30c9e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1008
VAR
    {attribute addProperty Name "CHANNEL_"}
    _io : EL1008_Data;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{6c23073f-b5eb-0168-3201-7bb4bc5aa64d}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1008_Data]]></Declaration>
      <Get Name="Get" Id="{829f0e6f-e293-0a6c-3ad0-2ca89e90c245}">
        <Declaration><![CDATA[VAR
END_VAR]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>