<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2652" Id="{36a4ffc6-5c8e-0cdc-2dd8-157daad6a086}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2652
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2xx2_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{25e0d1dc-845b-0525-0028-c39f9bfcb014}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2xx2_Data]]></Declaration>
      <Get Name="Get" Id="{e632106c-1d0c-0f81-1c86-db29851a0928}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{c52fe9a3-74ae-0a67-2bec-556cdefe2330}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{6eb53ca1-59bc-05ea-095c-819f8836a7ef}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>