<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2712" Id="{d5209774-0c46-0cb3-09ed-ef307dfb0bf0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2712
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2xx2_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{757ce4ff-b00b-01c7-2762-fb1bc9058f79}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2xx2_Data]]></Declaration>
      <Get Name="Get" Id="{bb2fa509-e493-0a76-3437-2b8df2489c1b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{ae97ac85-02f1-0800-2389-0a050daa27c0}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{23ad4620-939d-070b-2ca2-d4c1999eae07}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>