<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL4002" Id="{32d7d8a9-5e38-0286-31dd-d4e13cff88f1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL4002
VAR
	_io : EL4xx2_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{81dd9e16-1f7d-005a-2498-12f3053fa4e6}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL4xx2_Data]]></Declaration>
      <Get Name="Get" Id="{5e55e3a7-cea0-0b6c-3441-b0d61e3d044d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{06cd8af7-fa08-01c4-06f9-9e1dcbf6c756}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{fb0be06d-86a2-0187-158f-7bbfb04ecd54}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>