<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL4132" Id="{af29e7ca-ec8e-03b5-0353-b4d8aea9de07}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL4132
VAR
	_io : EL4xx2_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{803f0279-6366-038f-1c5c-3832470c896a}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL4xx2_Data]]></Declaration>
      <Get Name="Get" Id="{7c34a465-40d5-07af-11b8-6e988079bd1c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{c30af17a-082d-0ee8-3c03-709636ba4b58}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateBase]]></Declaration>
      <Get Name="Get" Id="{0f315138-6db1-0dc5-2b72-96801a2afdb5}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>