<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL5001" Id="{0ba7fb67-07c4-086c-2c6f-a2b1d6bdd0d9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL5001
VAR
	_io : EL5001_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAdsDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{0cc0a926-0b90-08b5-0807-5a2e978ab660}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL5001_Data]]></Declaration>
      <Get Name="Get" Id="{bb9f2061-5795-0187-0808-1db1a2c69f59}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{a84c976b-f306-07bc-3b0c-dd32fd815249}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{6a9cec77-093f-0e5a-3047-f2844330ceeb}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>