<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1809" Id="{4067506e-2852-0893-1edb-5fd46d2c9b67}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1809
VAR
	_io : EL1xx9_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{415dd3a3-b86b-0eec-0e7d-d787d2620359}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1xx9_Data]]></Declaration>
      <Get Name="Get" Id="{a493393d-bdfc-0184-390d-63ea75ea9ac2}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{a69a8bc8-4cba-082c-320a-349eec7066a2}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{cbfa59ec-71a9-03a3-2431-013c45d94bc0}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>