<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{6af77bf1-277e-0a98-2c35-6eb9f887cb1b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	_testContext : TcoBlinkerTestContext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_testContext.ProbeRun();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>