<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2521" Id="{c555ee9b-1332-0798-0c56-83aabb4a027f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2521
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
	_io : EL2521_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{467153c3-54a7-0ea4-2aca-7025e8fbba5b}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2521_Data]]></Declaration>
      <Get Name="Get" Id="{3bc72298-5893-0717-3a9e-8462f844ca79}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{23776a97-eb50-083e-1d21-e3e010a90d62}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{d58cba13-8ea7-08c4-092b-8eb7e713bacf}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>