<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1502" Id="{b546c49f-dcc9-058a-3ccb-9cb8b975d2f1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1502
VAR
	_io : EL1502_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{874e6a08-cba8-0ecc-3757-8e3daa76ff79}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1502_Data]]></Declaration>
      <Get Name="Get" Id="{50253678-e502-0a72-3006-b2192fcace6e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{f7c640bf-123c-08e4-1213-0dd7f1c40cb3}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{fed27eff-5ed8-08d9-044e-7b32bd77c0eb}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>