<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL5072" Id="{661530b7-05b4-0e2b-1f62-4917b3477550}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL5072
VAR
	_io : EL5072_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAdsDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{6b4da506-4d68-0203-3f0e-3d4ac373a747}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL5072_Data]]></Declaration>
      <Get Name="Get" Id="{093d218f-2306-0433-1c6e-e96dfb761d0c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{f46b6aa1-d311-0c8b-0754-4f1292f40484}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{5eff771d-076a-0e7e-0ced-5c120f7a2343}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>