<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL5112" Id="{c253403c-6401-0413-2176-25df190be463}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL5112
VAR
	_io : EL5112_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAdsDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{424bbc33-3487-08ab-20bd-47b9cc895834}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL5112_Data]]></Declaration>
      <Get Name="Get" Id="{c94b07ee-a2d7-000c-02d6-dc4315436a57}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{c247f607-1118-0b83-38ea-5f3735ea23e1}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{f004d7d0-03fa-0457-0b73-8a9df7734904}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>