//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoAbbRoboticsConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoAbbRoboticsConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action number.
        /// </summary>
        public static string ___Action_number__ {
            get {
                return ResourceManager.GetString("___Action_number__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual coordinates workobject tool.
        /// </summary>
        public static string ___Actual_coordinates_workobject_tool__ {
            get {
                return ResourceManager.GetString("___Actual_coordinates_workobject_tool__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual coordinates world.
        /// </summary>
        public static string ___Actual_coordinates_world__ {
            get {
                return ResourceManager.GetString("___Actual_coordinates_world__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto stop 1.
        /// </summary>
        public static string ___Auto_stop_1__ {
            get {
                return ResourceManager.GetString("___Auto_stop_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto stop 2.
        /// </summary>
        public static string ___Auto_stop_2__ {
            get {
                return ResourceManager.GetString("___Auto_stop_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoOn.
        /// </summary>
        public static string ___AutoOn__ {
            get {
                return ResourceManager.GetString("___AutoOn__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string ___Config__ {
            get {
                return ResourceManager.GetString("___Config__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller error, see teach pendant.
        /// </summary>
        public static string ___Controller_error__see_teach_pendant__ {
            get {
                return ResourceManager.GetString("___Controller_error__see_teach_pendant__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string ___Coordinates__ {
            get {
                return ResourceManager.GetString("___Coordinates__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycleOn.
        /// </summary>
        public static string ___CycleOn__ {
            get {
                return ResourceManager.GetString("___CycleOn__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceleration.
        /// </summary>
        public static string ___Deceleration__ {
            get {
                return ResourceManager.GetString("___Deceleration__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string ___Disabled__ {
            get {
                return ResourceManager.GetString("___Disabled__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive error no .
        /// </summary>
        public static string ___Drive_error_no___ {
            get {
                return ResourceManager.GetString("___Drive_error_no___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive power override.
        /// </summary>
        public static string ___Drive_power_override__ {
            get {
                return ResourceManager.GetString("___Drive_power_override__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop.
        /// </summary>
        public static string ___Emergency_stop__ {
            get {
                return ResourceManager.GetString("___Emergency_stop__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop 1.
        /// </summary>
        public static string ___Emergency_stop_1__ {
            get {
                return ResourceManager.GetString("___Emergency_stop_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop 2.
        /// </summary>
        public static string ___Emergency_stop_2__ {
            get {
                return ResourceManager.GetString("___Emergency_stop_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop acknowledge.
        /// </summary>
        public static string ___Emergency_stop_acknowledge__ {
            get {
                return ResourceManager.GetString("___Emergency_stop_acknowledge__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop active.
        /// </summary>
        public static string ___Emergency_stop_active__ {
            get {
                return ResourceManager.GetString("___Emergency_stop_active__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 1.
        /// </summary>
        public static string ___Enable_1__ {
            get {
                return ResourceManager.GetString("___Enable_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 2.
        /// </summary>
        public static string ___Enable_2__ {
            get {
                return ResourceManager.GetString("___Enable_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement out off area 1.
        /// </summary>
        public static string ___Enable_movement_out_off_area_1__ {
            get {
                return ResourceManager.GetString("___Enable_movement_out_off_area_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement out off area 2.
        /// </summary>
        public static string ___Enable_movement_out_off_area_2__ {
            get {
                return ResourceManager.GetString("___Enable_movement_out_off_area_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement out off area 3.
        /// </summary>
        public static string ___Enable_movement_out_off_area_3__ {
            get {
                return ResourceManager.GetString("___Enable_movement_out_off_area_3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement out off area 4.
        /// </summary>
        public static string ___Enable_movement_out_off_area_4__ {
            get {
                return ResourceManager.GetString("___Enable_movement_out_off_area_4__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement out off area 5.
        /// </summary>
        public static string ___Enable_movement_out_off_area_5__ {
            get {
                return ResourceManager.GetString("___Enable_movement_out_off_area_5__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement out off area 6.
        /// </summary>
        public static string ___Enable_movement_out_off_area_6__ {
            get {
                return ResourceManager.GetString("___Enable_movement_out_off_area_6__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement out off area 7.
        /// </summary>
        public static string ___Enable_movement_out_off_area_7__ {
            get {
                return ResourceManager.GetString("___Enable_movement_out_off_area_7__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement out off area 8.
        /// </summary>
        public static string ___Enable_movement_out_off_area_8__ {
            get {
                return ResourceManager.GetString("___Enable_movement_out_off_area_8__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement to area 1.
        /// </summary>
        public static string ___Enable_movement_to_area_1__ {
            get {
                return ResourceManager.GetString("___Enable_movement_to_area_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement to area 2.
        /// </summary>
        public static string ___Enable_movement_to_area_2__ {
            get {
                return ResourceManager.GetString("___Enable_movement_to_area_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement to area 3.
        /// </summary>
        public static string ___Enable_movement_to_area_3__ {
            get {
                return ResourceManager.GetString("___Enable_movement_to_area_3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement to area 4.
        /// </summary>
        public static string ___Enable_movement_to_area_4__ {
            get {
                return ResourceManager.GetString("___Enable_movement_to_area_4__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement to area 5.
        /// </summary>
        public static string ___Enable_movement_to_area_5__ {
            get {
                return ResourceManager.GetString("___Enable_movement_to_area_5__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement to area 6.
        /// </summary>
        public static string ___Enable_movement_to_area_6__ {
            get {
                return ResourceManager.GetString("___Enable_movement_to_area_6__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement to area 7.
        /// </summary>
        public static string ___Enable_movement_to_area_7__ {
            get {
                return ResourceManager.GetString("___Enable_movement_to_area_7__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable movement to area 8.
        /// </summary>
        public static string ___Enable_movement_to_area_8__ {
            get {
                return ResourceManager.GetString("___Enable_movement_to_area_8__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable negative.
        /// </summary>
        public static string ___Enable_negative__ {
            get {
                return ResourceManager.GetString("___Enable_negative__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable positive.
        /// </summary>
        public static string ___Enable_positive__ {
            get {
                return ResourceManager.GetString("___Enable_positive__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ___Enabled__ {
            get {
                return ResourceManager.GetString("___Enabled__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ___Error__ {
            get {
                return ResourceManager.GetString("___Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error acknowledge.
        /// </summary>
        public static string ___Error_acknowledge__ {
            get {
                return ResourceManager.GetString("___Error_acknowledge__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General stop 1.
        /// </summary>
        public static string ___General_stop_1__ {
            get {
                return ResourceManager.GetString("___General_stop_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General stop 2.
        /// </summary>
        public static string ___General_stop_2__ {
            get {
                return ResourceManager.GetString("___General_stop_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global control.
        /// </summary>
        public static string ___Global_control__ {
            get {
                return ResourceManager.GetString("___Global_control__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global robot speed.
        /// </summary>
        public static string ___Global_robot_speed__ {
            get {
                return ResourceManager.GetString("___Global_robot_speed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global speed.
        /// </summary>
        public static string ___Global_speed__ {
            get {
                return ResourceManager.GetString("___Global_speed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt.
        /// </summary>
        public static string ___Halt__ {
            get {
                return ResourceManager.GetString("___Halt__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        public static string ___IN__ {
            get {
                return ResourceManager.GetString("___IN__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 1.
        /// </summary>
        public static string ___In_area_1__ {
            get {
                return ResourceManager.GetString("___In_area_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 2.
        /// </summary>
        public static string ___In_area_2__ {
            get {
                return ResourceManager.GetString("___In_area_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 3.
        /// </summary>
        public static string ___In_area_3__ {
            get {
                return ResourceManager.GetString("___In_area_3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 4.
        /// </summary>
        public static string ___In_area_4__ {
            get {
                return ResourceManager.GetString("___In_area_4__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 5.
        /// </summary>
        public static string ___In_area_5__ {
            get {
                return ResourceManager.GetString("___In_area_5__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 6.
        /// </summary>
        public static string ___In_area_6__ {
            get {
                return ResourceManager.GetString("___In_area_6__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 7.
        /// </summary>
        public static string ___In_area_7__ {
            get {
                return ResourceManager.GetString("___In_area_7__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In area 8.
        /// </summary>
        public static string ___In_area_8__ {
            get {
                return ResourceManager.GetString("___In_area_8__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In home position.
        /// </summary>
        public static string ___In_home_position__ {
            get {
                return ResourceManager.GetString("___In_home_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 1.
        /// </summary>
        public static string ___In_position_1__ {
            get {
                return ResourceManager.GetString("___In_position_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 2.
        /// </summary>
        public static string ___In_position_2__ {
            get {
                return ResourceManager.GetString("___In_position_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 3.
        /// </summary>
        public static string ___In_position_3__ {
            get {
                return ResourceManager.GetString("___In_position_3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 4.
        /// </summary>
        public static string ___In_position_4__ {
            get {
                return ResourceManager.GetString("___In_position_4__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 5.
        /// </summary>
        public static string ___In_position_5__ {
            get {
                return ResourceManager.GetString("___In_position_5__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 6.
        /// </summary>
        public static string ___In_position_6__ {
            get {
                return ResourceManager.GetString("___In_position_6__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 7.
        /// </summary>
        public static string ___In_position_7__ {
            get {
                return ResourceManager.GetString("___In_position_7__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In position 8.
        /// </summary>
        public static string ___In_position_8__ {
            get {
                return ResourceManager.GetString("___In_position_8__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In service position.
        /// </summary>
        public static string ___In_service_position__ {
            get {
                return ResourceManager.GetString("___In_service_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interuption actually running instruction.
        /// </summary>
        public static string ___Interuption_actually_running_instruction__ {
            get {
                return ResourceManager.GetString("___Interuption_actually_running_instruction__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reference: .
        /// </summary>
        public static string ___Invalid_reference____ {
            get {
                return ResourceManager.GetString("___Invalid_reference____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerk.
        /// </summary>
        public static string ___Jerk__ {
            get {
                return ResourceManager.GetString("___Jerk__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load and run program.
        /// </summary>
        public static string ___Load_and_run_program__ {
            get {
                return ResourceManager.GetString("___Load_and_run_program__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load program.
        /// </summary>
        public static string ___Load_program__ {
            get {
                return ResourceManager.GetString("___Load_program__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local control.
        /// </summary>
        public static string ___Local_control__ {
            get {
                return ResourceManager.GetString("___Local_control__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name.
        /// </summary>
        public static string ___Module_name__ {
            get {
                return ResourceManager.GetString("___Module_name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor off.
        /// </summary>
        public static string ___Motor_off__ {
            get {
                return ResourceManager.GetString("___Motor_off__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor off state.
        /// </summary>
        public static string ___Motor_off_state__ {
            get {
                return ResourceManager.GetString("___Motor_off_state__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor on.
        /// </summary>
        public static string ___Motor_on__ {
            get {
                return ResourceManager.GetString("___Motor_on__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor on state.
        /// </summary>
        public static string ___Motor_on_state__ {
            get {
                return ResourceManager.GetString("___Motor_on_state__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move active.
        /// </summary>
        public static string ___Move_active__ {
            get {
                return ResourceManager.GetString("___Move_active__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move inactive.
        /// </summary>
        public static string ___Move_inactive__ {
            get {
                return ResourceManager.GetString("___Move_inactive__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement was aborted, while not yet completed!.
        /// </summary>
        public static string ___Movement_was_aborted__while_not_yet_completed___ {
            get {
                return ResourceManager.GetString("___Movement_was_aborted__while_not_yet_completed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to position ID.
        /// </summary>
        public static string ___Moving_to_position_ID__ {
            get {
                return ResourceManager.GetString("___Moving_to_position_ID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT.
        /// </summary>
        public static string ___OUT__ {
            get {
                return ResourceManager.GetString("___OUT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out off home position.
        /// </summary>
        public static string ___Out_off_home_position__ {
            get {
                return ResourceManager.GetString("___Out_off_home_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out off service position.
        /// </summary>
        public static string ___Out_off_service_position__ {
            get {
                return ResourceManager.GetString("___Out_off_service_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string ___Override__ {
            get {
                return ResourceManager.GetString("___Override__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point number.
        /// </summary>
        public static string ___Point_number__ {
            get {
                return ResourceManager.GetString("___Point_number__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PointNumber.
        /// </summary>
        public static string ___PointNumber__ {
            get {
                return ResourceManager.GetString("___PointNumber__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string ___Power__ {
            get {
                return ResourceManager.GetString("___Power__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power enable.
        /// </summary>
        public static string ___Power_enable__ {
            get {
                return ResourceManager.GetString("___Power_enable__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program execution error.
        /// </summary>
        public static string ___Program_execution_error__ {
            get {
                return ResourceManager.GetString("___Program_execution_error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program execution error see robot panel for details.
        /// </summary>
        public static string ___Program_execution_error_see_robot_panel_for_details__ {
            get {
                return ResourceManager.GetString("___Program_execution_error_see_robot_panel_for_details__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program start.
        /// </summary>
        public static string ___Program_start__ {
            get {
                return ResourceManager.GetString("___Program_start__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program start at main.
        /// </summary>
        public static string ___Program_start_at_main__ {
            get {
                return ResourceManager.GetString("___Program_start_at_main__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program stop.
        /// </summary>
        public static string ___Program_stop__ {
            get {
                return ResourceManager.GetString("___Program_stop__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ___Reset__ {
            get {
                return ResourceManager.GetString("___Reset__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot not switched in auto mode.
        /// </summary>
        public static string ___Robot_not_switched_in_auto_mode__ {
            get {
                return ResourceManager.GetString("___Robot_not_switched_in_auto_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety chanin OK.
        /// </summary>
        public static string ___Safety_chanin_OK__ {
            get {
                return ResourceManager.GetString("___Safety_chanin_OK__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety circuit open.
        /// </summary>
        public static string ___Safety_circuit_open__ {
            get {
                return ResourceManager.GetString("___Safety_circuit_open__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety interupted.
        /// </summary>
        public static string ___Safety_interupted__ {
            get {
                return ResourceManager.GetString("___Safety_interupted__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed limitation.
        /// </summary>
        public static string ___Speed_limitation__ {
            get {
                return ResourceManager.GetString("___Speed_limitation__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start movements.
        /// </summary>
        public static string ___Start_movements__ {
            get {
                return ResourceManager.GetString("___Start_movements__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ___Status__ {
            get {
                return ResourceManager.GetString("___Status__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop movement-quick.
        /// </summary>
        public static string ___Stop_movement_quick__ {
            get {
                return ResourceManager.GetString("___Stop_movement_quick__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop movement-soft.
        /// </summary>
        public static string ___Stop_movement_soft__ {
            get {
                return ResourceManager.GetString("___Stop_movement_soft__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop movements.
        /// </summary>
        public static string ___Stop_movements__ {
            get {
                return ResourceManager.GetString("___Stop_movements__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop program at the end of the cycle.
        /// </summary>
        public static string ___Stop_program_at_the_end_of_the_cycle__ {
            get {
                return ResourceManager.GetString("___Stop_program_at_the_end_of_the_cycle__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop program at the end of the instruction.
        /// </summary>
        public static string ___Stop_program_at_the_end_of_the_instruction__ {
            get {
                return ResourceManager.GetString("___Stop_program_at_the_end_of_the_instruction__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping movement finished with error..
        /// </summary>
        public static string ___Stopping_movement_finished_with_error___ {
            get {
                return ResourceManager.GetString("___Stopping_movement_finished_with_error___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping movements was completed successfully..
        /// </summary>
        public static string ___Stopping_movements_was_completed_successfully___ {
            get {
                return ResourceManager.GetString("___Stopping_movements_was_completed_successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping started..
        /// </summary>
        public static string ___Stopping_started___ {
            get {
                return ResourceManager.GetString("___Stopping_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch off the motors.
        /// </summary>
        public static string ___Switch_off_the_motors__ {
            get {
                return ResourceManager.GetString("___Switch_off_the_motors__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch on the motors.
        /// </summary>
        public static string ___Switch_on_the_motors__ {
            get {
                return ResourceManager.GetString("___Switch_on_the_motors__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch on the motors and start program.
        /// </summary>
        public static string ___Switch_on_the_motors_and_start_program__ {
            get {
                return ResourceManager.GetString("___Switch_on_the_motors_and_start_program__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 1 extend.
        /// </summary>
        public static string ___Tool_1_extend__ {
            get {
                return ResourceManager.GetString("___Tool_1_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 1 retract.
        /// </summary>
        public static string ___Tool_1_retract__ {
            get {
                return ResourceManager.GetString("___Tool_1_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 2 extend.
        /// </summary>
        public static string ___Tool_2_extend__ {
            get {
                return ResourceManager.GetString("___Tool_2_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 2 retract.
        /// </summary>
        public static string ___Tool_2_retract__ {
            get {
                return ResourceManager.GetString("___Tool_2_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 3 extend.
        /// </summary>
        public static string ___Tool_3_extend__ {
            get {
                return ResourceManager.GetString("___Tool_3_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 3 retract.
        /// </summary>
        public static string ___Tool_3_retract__ {
            get {
                return ResourceManager.GetString("___Tool_3_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 4 extend.
        /// </summary>
        public static string ___Tool_4_extend__ {
            get {
                return ResourceManager.GetString("___Tool_4_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 4 retract.
        /// </summary>
        public static string ___Tool_4_retract__ {
            get {
                return ResourceManager.GetString("___Tool_4_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 5 extend.
        /// </summary>
        public static string ___Tool_5_extend__ {
            get {
                return ResourceManager.GetString("___Tool_5_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 5 retract.
        /// </summary>
        public static string ___Tool_5_retract__ {
            get {
                return ResourceManager.GetString("___Tool_5_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 6 extend.
        /// </summary>
        public static string ___Tool_6_extend__ {
            get {
                return ResourceManager.GetString("___Tool_6_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 6 retract.
        /// </summary>
        public static string ___Tool_6_retract__ {
            get {
                return ResourceManager.GetString("___Tool_6_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 7 extend.
        /// </summary>
        public static string ___Tool_7_extend__ {
            get {
                return ResourceManager.GetString("___Tool_7_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 7 retract.
        /// </summary>
        public static string ___Tool_7_retract__ {
            get {
                return ResourceManager.GetString("___Tool_7_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 8 extend.
        /// </summary>
        public static string ___Tool_8_extend__ {
            get {
                return ResourceManager.GetString("___Tool_8_extend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool 8 retract.
        /// </summary>
        public static string ___Tool_8_retract__ {
            get {
                return ResourceManager.GetString("___Tool_8_retract__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool number.
        /// </summary>
        public static string ___Tool_number__ {
            get {
                return ResourceManager.GetString("___Tool_number__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error see robots panel for details.
        /// </summary>
        public static string ___Unspecified_error_see_robots_panel_for_details__ {
            get {
                return ResourceManager.GetString("___Unspecified_error_see_robots_panel_for_details__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User specific speed 1.
        /// </summary>
        public static string ___User_specific_speed_1__ {
            get {
                return ResourceManager.GetString("___User_specific_speed_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User specific speed 2.
        /// </summary>
        public static string ___User_specific_speed_2__ {
            get {
                return ResourceManager.GetString("___User_specific_speed_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workobject number.
        /// </summary>
        public static string ___Workobject_number__ {
            get {
                return ResourceManager.GetString("___Workobject_number__", resourceCulture);
            }
        }
    }
}
