<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="TcoTier" Id="{b03c48ad-ab45-0697-3bbf-4f1922cef1af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcoTier EXTENDS TcoCore.TcoObject
VAR
	_nextExpectedCycle : ULINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{ff9e5ffa-34d3-0196-37e7-07844c34c44c}">
      <Declaration><![CDATA[{attribute 'hide'}
METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	ParentObject : ITcoObject;	
END_VAR


]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="IsNewTier" Id="{f55c3d87-5b7f-04ae-3379-eb9ac260e42d}">
      <Declaration><![CDATA[METHOD IsNewTier : BOOL

]]></Declaration>
      <Implementation>
        <ST><![CDATA[IsNewTier := THIS^.Context.StartCycleCount <> _nextExpectedCycle;
_nextExpectedCycle := THIS^.Context.StartCycleCount + 1;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>