<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="TcoDataManager" Id="{cbedc24e-3653-0ddc-2b27-80848f6cc570}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcoDataManager EXTENDS TcoData.TcoDataExchange
VAR
    _data : Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>