<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2809" Id="{a5d8806d-2fa9-0a34-239c-97db45246e10}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2809
VAR
	{attribute addProperty Name "CHANNEL_"}
	_io : EL2809_Data;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_infoData();]]></ST>
    </Implementation>
    <Property Name="IO" Id="{85b3b5a7-679e-0afe-1f4f-a394a1bac951}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2809_Data]]></Declaration>
      <Get Name="Get" Id="{02ea8413-b717-0fcd-2401-f6ab7af0ed4d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>