<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL2032" Id="{c9ac5850-9e39-0f29-39ae-8752722b4294}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2032
VAR
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
	_io : EL2032_Data;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{f8913651-3560-06fd-1b13-eb5db7c0a545}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL2032_Data]]></Declaration>
      <Get Name="Get" Id="{c25f3e96-7b1e-01d7-12af-99479cfd2d18}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{d0f3d198-7039-0356-0115-4457b7bac1bb}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{ed1ebc52-42e5-063f-121d-5d474b24b1e1}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>