//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcoCoreConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcoCoreConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current step.
        /// </summary>
        public static string ___Current_step__ {
            get {
                return ResourceManager.GetString("___Current_step__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ___Enabled__ {
            get {
                return ResourceManager.GetString("___Enabled__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke request.
        /// </summary>
        public static string ___Invoke_request__ {
            get {
                return ResourceManager.GetString("___Invoke_request__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore request.
        /// </summary>
        public static string ___Restore_request__ {
            get {
                return ResourceManager.GetString("___Restore_request__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequencer error.
        /// </summary>
        public static string ___Sequencer_error__ {
            get {
                return ResourceManager.GetString("___Sequencer_error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequencer error ID.
        /// </summary>
        public static string ___Sequencer_error_ID__ {
            get {
                return ResourceManager.GetString("___Sequencer_error_ID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step description.
        /// </summary>
        public static string ___Step_description__ {
            get {
                return ResourceManager.GetString("___Step_description__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step duration.
        /// </summary>
        public static string ___Step_duration__ {
            get {
                return ResourceManager.GetString("___Step_duration__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step ID.
        /// </summary>
        public static string ___Step_ID__ {
            get {
                return ResourceManager.GetString("___Step_ID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Order.
        /// </summary>
        public static string ___Step_Order__ {
            get {
                return ResourceManager.GetString("___Step_Order__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step status.
        /// </summary>
        public static string ___Step_status__ {
            get {
                return ResourceManager.GetString("___Step_status__", resourceCulture);
            }
        }
    }
}
