<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="SampleComponentTests" Id="{59d24b2c-148b-081d-164b-e04a36fdd44a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SampleComponentTests EXTENDS TcoCore._internals_TcoContext
VAR
	_sut : TcoIoBeckhoff.SampleComponent(THIS^);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <Method Name="AddTwoNumbersTest" Id="{9c2bb0cc-4b78-00fe-3a26-c17460dad23a}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD INTERNAL AddTwoNumbersTest : INT
VAR_INPUT
	NumberOne : INT;
	NumberTwo : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[AddTwoNumbersTest := _sut.AddTwoNumbers(NumberOne, NumberTwo);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Main" Id="{f9c63a21-8864-04ed-1cb7-fda475bab4cf}">
      <Declaration><![CDATA[METHOD PROTECTED Main
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="WaitForModuloTest" Id="{1620f468-f32b-0f25-0b1d-f21773abde6d}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD INTERNAL WaitForModuloTest : BOOL
VAR_INPUT
	Modulo : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[WaitForModuloTest := _sut.WaitForModulo(Modulo);
	]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>