<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL5032" Id="{5df5ba9f-87c0-04cf-24eb-af68c8e96dbb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL5032
VAR
	_io : EL5032_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAdsDC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{461b1b9f-dab3-053d-391b-48d39b291e56}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL5032_Data]]></Declaration>
      <Get Name="Get" Id="{4a31f5d1-ad95-0000-0ecb-5076435ff80d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{a3e61491-658b-0072-2f55-149918791a45}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{b8be0cf3-8e1a-02cc-333e-d0513c6cf941}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>