<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SequenceTask" Id="{e15a7e44-44eb-0998-2972-35c98aeea6f7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SequenceTask EXTENDS TcoCore.TcoTask
VAR_INPUT
	Sequence : TcoCore.ITcoSequencer;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Restore" Id="{5dfb53ad-7987-0b17-386e-336346a13e2f}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Restores this instance to the Ready state. Can be called explicitly or from within one of the restore mechanisms.
			<para>
				See also <see cref="PlcDocu.TcoCore.TcoTask.AutoRestorable()"/>
			</para>
		</summary>			
	</docu>	
~*)
METHOD Restore : ITcoRestorable]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.Restore();
THIS^.Sequence.Restore();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>