<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3154" Id="{18f8760f-82fc-07ae-04e5-e8f902630ac2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3154
VAR
	_io : EL3xx4_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{909dbbc9-ace7-00ee-204d-0d19fdea600c}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3xx4_Data]]></Declaration>
      <Get Name="Get" Id="{c144c5cc-720c-0cc6-08b1-22c155aa3fb6}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{23e95868-0cb7-0c9c-1966-2306c08320d7}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{30ed9d74-5b6f-0cb2-07ee-617ba5e20c4a}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>