<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3692" Id="{b79d3e60-94d9-0773-1124-921aac75faa8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3692
VAR
	_io : EL3692_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{1da20d02-b90f-0339-0ee7-08e21e71fdac}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3692_Data]]></Declaration>
      <Get Name="Get" Id="{722f0b99-4fcc-03c8-0fc6-174f9288db5f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{4f22e249-12b7-01d3-3102-e7795eb2644d}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{7df7f459-794f-01bf-34bb-0c29fd5d2cf7}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>