//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcOpen.Inxton.TcoDrivesBeckhoff.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcOpen.Inxton.TcoDrivesBeckhoff.Wpf.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc..
        /// </summary>
        public static string Acc {
            get {
                return ResourceManager.GetString("Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to create new set?.
        /// </summary>
        public static string AskCreate {
            get {
                return ResourceManager.GetString("AskCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete set?.
        /// </summary>
        public static string AskDelete {
            get {
                return ResourceManager.GetString("AskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to load positions?.
        /// </summary>
        public static string AskLoad {
            get {
                return ResourceManager.GetString("AskLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to move position:.
        /// </summary>
        public static string AskMovePos {
            get {
                return ResourceManager.GetString("AskMovePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to save positions?.
        /// </summary>
        public static string AskSave {
            get {
                return ResourceManager.GetString("AskSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change position:.
        /// </summary>
        public static string AskTeachPos {
            get {
                return ResourceManager.GetString("AskTeachPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis.
        /// </summary>
        public static string Axis {
            get {
                return ResourceManager.GetString("Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec..
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceleration.
        /// </summary>
        public static string Deceleration {
            get {
                return ResourceManager.GetString("Deceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Repository Handler first!.
        /// </summary>
        public static string DefineRepository {
            get {
                return ResourceManager.GetString("DefineRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerk.
        /// </summary>
        public static string Jerk {
            get {
                return ResourceManager.GetString("Jerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to position.
        /// </summary>
        public static string MoveToPosition {
            get {
                return ResourceManager.GetString("MoveToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select position first!.
        /// </summary>
        public static string SelectFirst {
            get {
                return ResourceManager.GetString("SelectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SetId first!.
        /// </summary>
        public static string SelectSetId {
            get {
                return ResourceManager.GetString("SelectSetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Id.
        /// </summary>
        public static string SetId {
            get {
                return ResourceManager.GetString("SetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write SetId first!.
        /// </summary>
        public static string SetNewName {
            get {
                return ResourceManager.GetString("SetNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teach.
        /// </summary>
        public static string Teach {
            get {
                return ResourceManager.GetString("Teach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vel..
        /// </summary>
        public static string Vel {
            get {
                return ResourceManager.GetString("Vel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write default values.
        /// </summary>
        public static string WriteDefaultValues {
            get {
                return ResourceManager.GetString("WriteDefaultValues", resourceCulture);
            }
        }
    }
}
