<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Color_Example" Id="{fddaf6ce-57e1-0249-2035-324e7a4e9c4d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Color_Example EXTENDS TcoCore.TcoContext
VAR
	ColorSequencer : ColorSequencer(THIS^, eRestoreMode.AutoRestoreMembers) ;
	Colors : stColors;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Use Main method instead of this block.]]></ST>
    </Implementation>
    <Method Name="Main" Id="{01796224-0f15-09e4-2621-dd6d8246d174}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Main method of the TcoContext. This is the entry point of any control logic that belongs to this context. 
			The call of this method is ensured by calling the <c>InstanceName.Run()</c> method, and it must not be called explicitly.
			This method is abstract, and it must be overridden in derived block.
		</summary>
	</docu>
~*)
METHOD PROTECTED  Main]]></Declaration>
      <Implementation>
        <ST><![CDATA[ColorSequencer( 
	inoColors := Colors
);

ColorSequencer.Run();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>