<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="fbInheritanceLevel_4" Id="{ba63cbe9-92bb-4b9b-8666-6c548873f4d8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbInheritanceLevel_4 EXTENDS fbInheritanceLevel_3
VAR
	{attribute addProperty Name "LEVEL 4"}
	level_4 : stAllTypes;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
    <Method Name="Init" Id="{b14964ff-8deb-4680-8a1b-107600890b21}">
      <Declaration><![CDATA[METHOD Init : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.Init();]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="fbInheritanceLevel_4">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="fbInheritanceLevel_4.Init">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>