<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="fbInheritanceLevel_5" Id="{74807b99-3731-41e6-9f64-0e44d94b184c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbInheritanceLevel_5 EXTENDS fbInheritanceLevel_4
VAR
	{attribute addProperty Name "LEVEL 5"}
	level_5 : stAllTypes;			
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Init" Id="{582b02c7-0761-4a1c-9aa6-e674b19e672f}">
      <Declaration><![CDATA[METHOD Init : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.Init();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>