<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL1852" Id="{bb4d4acb-152a-0c50-2320-5e1213478461}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1852
VAR
	_io : EL1852_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{32513370-056b-074a-2ae2-853942cf88e9}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL1852_Data]]></Declaration>
      <Get Name="Get" Id="{e38ab64c-f18c-0485-2c79-85e58aa83426}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{7f3f956c-ca84-06a4-0f71-3fa3a6645423}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{c4a72177-5c08-0088-225b-3a47f6e4f5a5}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>