<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EL3001" Id="{00ca6e78-ad1d-0c27-3710-d424f43db701}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3001
VAR
	_io : EL3xx1_Data;
	{attribute addProperty Name "WcState"}
	_wcState : WcStateInputToggle;
	{attribute addProperty Name "Info data"}
	_infoData : InfoDataAds;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IO" Id="{842e7815-184d-01e6-2fe6-6f39e76935dd}">
      <Declaration><![CDATA[PROPERTY IO : REFERENCE TO EL3xx1_Data]]></Declaration>
      <Get Name="Get" Id="{3e24745a-b35c-03f2-2e00-54d3bd5a64dd}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IO REF= _io;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WcState" Id="{88fd9bca-c6d8-0de4-2aee-5ead4f3337ee}">
      <Declaration><![CDATA[PROPERTY WcState : REFERENCE TO WcStateInputToggle]]></Declaration>
      <Get Name="Get" Id="{7a0e0394-be28-0593-0330-e20111d92340}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[WcState REF= _wcState;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>