<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MANIPULATOR" Id="{46649b69-6523-450e-95e7-0d33168f6b81}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MANIPULATOR
VAR
	_context : fbManipulatorContext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_context.Run();]]></ST>
    </Implementation>
    <LineIds Name="MANIPULATOR">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>