name: dev

on: 
  push:
    branches : 
      - dev
  pull_request: 
    paths:
      - 'src/**'
      - 'pipelines/**'
      - '.github/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it. Dummy edit
      - uses: actions/checkout@v2
      # Check if the action works
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Fetch unshallow
        run: git fetch --unshallow
      # Run psake
      - name: Run a multi-line script
        run: |
          .\pipelines\runbuild.ps1 -properties @{"buildConfig" = "Release";  "updateAssemblyInfo" = $true; "testingStrength" = 1; "isTestingEnabled" = $true; "packNugets" = $false;}
      - name : Create Tag
        if : env.BuildNumber && success() && github.event_name != 'pull_request'
        run : |
          git config --global user.email "gh-action@tcopengroup.com"
          git config --global user.name "gh-action"
          $tag = "GH-${{github.run_id}}-${{env.BuildNumber}}"
          git tag $tag 
          git push --tags
        continue-on-error: true
      - name: Upload test results
        uses: actions/upload-artifact@v2 
        if: success() || failure() 
        with:
          name: test-results
          path: ${{ github.workspace }}\**\TestResults\*.xml
      - name: Upload PLC libraries
        uses: actions/upload-artifact@v2 
        if: success() 
        with:
          name: plcLibs
          path: ${{ github.workspace }}\plcLibs\*.library
