name: Build

on: [push, pull_request, workflow_dispatch]
  # Allows you to run this workflow manually from the Actions tab
jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it. Dummy edit
      - uses: actions/checkout@v2
      # Check if the action works
      - name: Run a one-line script
        run: echo Hello, world!
      # Run psake
      - name: Run a multi-line script
        run: |
          .\pipelines\runbuild.ps1 -properties @{"buildConfig" = "Release"}
