name: dev

on: 
  push:
    branches : 
      - dev
  pull_request: 
    paths:
      - 'src/**'
      - 'pipelines/**'
      - '.github/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with :
          path : '.'
          fetch-depth: 0
      - name: Run Psake
        env:
          _PK_PHOENY_ : ${{ secrets._PK_PHOENY_  }}
          _TK_PHOENY_ : ${{ secrets._TK_PHOENY_  }}
          _TW_PHOENY : ${{ secrets._TW_PHOENY  }}
          _TW_TOKEN_ : ${{ secrets._TW_TOKEN_  }}
          _TW_USER_ : ${{ secrets._TW_USER_  }}
        run: >
          .\pipelines\runbuild.ps1 -properties 
          @{
            "buildConfig" = "Release";
            "updateAssemblyInfo" = $true;
            "testingStrength" = 1;
            "isTestingEnabled" = $true;
            "packNugets" = $false;
            }
      - name : Create Tag
        if : env.BuildNumber && success() && github.event_name != 'pull_request'
        run : |
          git config --global user.email "gh-action@tcopengroup.com"
          git config --global user.name "gh-action"
          $tag = "GH-${{github.run_id}}-${{env.BuildNumber}}"
          git tag $tag 
          git push --tags
        continue-on-error: true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test report
          path: '**/TestResults/*.xml'   
          reporter: dotnet-trx
      - name: Upload PLC libraries
        uses: actions/upload-artifact@v2 
        if: success() 
        with:
          name: plcLibs 
          path: ${{ github.workspace }}\plcLibs\*.library
