name: publish_packages

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Fetch unshallow
        run: git fetch --unshallow
      - name: Run a multi-line script
        run: |
          .\pipelines\runbuild.ps1 -properties @{"buildConfig" = "Release";  "updateAssemblyInfo" = $true; "publishNugets" = $true;}