name: 'Test Report'
on:
  workflow_run:
    workflows: ['Build','Nightly']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            
        name: Test report
        path: '**/*.xml'
        reporter: dotnet-trx