<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_CylinderTestAlternative" Id="{721255ca-134a-4131-8eee-ee5e15e5be2f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK INTERNAL FB_CylinderTestAlternative
VAR
	fbCylinder : fbCylinder;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="MoveCylinderToHome" Id="{3a42f3af-fba8-4502-bcfe-dbc0031d9218}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD MoveCylinderToHome : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[MoveCylinderToHome := fbCylinder.MoveToHome();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="MoveCylinderToWork" Id="{5e3db9ed-2149-436d-bf64-583f9bd6bf1d}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD MoveCylinderToWork : BOOL

]]></Declaration>
      <Implementation>
        <ST><![CDATA[MoveCylinderToWork := fbCylinder.MoveToWork();
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_CylinderTestAlternative">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_CylinderTestAlternative.MoveCylinderToHome">
      <LineId Id="55" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_CylinderTestAlternative.MoveCylinderToWork">
      <LineId Id="51" Count="0" />
      <LineId Id="44" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>